// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/templates/base.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stack creating/selecting subscription and networking
type Base struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StackName        string                 `protobuf:"bytes,1,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ProviderVersions []*ProviderVersion     `protobuf:"bytes,2,rep,name=provider_versions,json=providerVersions,proto3" json:"provider_versions,omitempty"`
	DependsOn        []TemplateOptions      `protobuf:"varint,3,rep,packed,name=depends_on,json=dependsOn,proto3,enum=proto.templates.TemplateOptions" json:"depends_on,omitempty"`
	Request          *BaseRequest           `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response         *BaseResponse          `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"` // leave empty when making requests
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_proto_templates_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *Base) GetProviderVersions() []*ProviderVersion {
	if x != nil {
		return x.ProviderVersions
	}
	return nil
}

func (x *Base) GetDependsOn() []TemplateOptions {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Base) GetRequest() *BaseRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Base) GetResponse() *BaseResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type BaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefaultParams  *DefaultParams         `protobuf:"bytes,1,opt,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty"`
	Subscription   *SubscriptionArgs      `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	VirtualNetwork *NetworkArgs           `protobuf:"bytes,3,opt,name=virtual_network,json=virtualNetwork,proto3" json:"virtual_network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_proto_templates_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetDefaultParams() *DefaultParams {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *BaseRequest) GetSubscription() *SubscriptionArgs {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *BaseRequest) GetVirtualNetwork() *NetworkArgs {
	if x != nil {
		return x.VirtualNetwork
	}
	return nil
}

type BaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	VnetId         string                 `protobuf:"bytes,2,opt,name=vnet_id,json=vnetId,proto3" json:"vnet_id,omitempty"`
	Subnets        []*SubnetResponse      `protobuf:"bytes,3,rep,name=subnets,proto3" json:"subnets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_proto_templates_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *BaseResponse) GetVnetId() string {
	if x != nil {
		return x.VnetId
	}
	return ""
}

func (x *BaseResponse) GetSubnets() []*SubnetResponse {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type SubscriptionArgs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId    string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // if not set, create a subscription using the env and project name in the format of "[{Environment}] Client Project: {ProjectName}"
	BillingScope      string                 `protobuf:"bytes,2,opt,name=billing_scope,json=billingScope,proto3" json:"billing_scope,omitempty"`
	ManagementGroupId string                 `protobuf:"bytes,3,opt,name=management_group_id,json=managementGroupId,proto3" json:"management_group_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscriptionArgs) Reset() {
	*x = SubscriptionArgs{}
	mi := &file_proto_templates_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionArgs) ProtoMessage() {}

func (x *SubscriptionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionArgs.ProtoReflect.Descriptor instead.
func (*SubscriptionArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionArgs) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionArgs) GetBillingScope() string {
	if x != nil {
		return x.BillingScope
	}
	return ""
}

func (x *SubscriptionArgs) GetManagementGroupId() string {
	if x != nil {
		return x.ManagementGroupId
	}
	return ""
}

type NetworkArgs struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	IpamPoolPrefixAllocations *IpamPoolPrefixAllocation `protobuf:"bytes,1,opt,name=ipam_pool_prefix_allocations,json=ipamPoolPrefixAllocations,proto3" json:"ipam_pool_prefix_allocations,omitempty"` // required (will error if not set)
	Subnets                   []*SubnetArgs             `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *NetworkArgs) Reset() {
	*x = NetworkArgs{}
	mi := &file_proto_templates_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkArgs) ProtoMessage() {}

func (x *NetworkArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkArgs.ProtoReflect.Descriptor instead.
func (*NetworkArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkArgs) GetIpamPoolPrefixAllocations() *IpamPoolPrefixAllocation {
	if x != nil {
		return x.IpamPoolPrefixAllocations
	}
	return nil
}

func (x *NetworkArgs) GetSubnets() []*SubnetArgs {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type SubnetArgs struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfIpAddresses int32                  `protobuf:"varint,2,opt,name=number_of_ip_addresses,json=numberOfIpAddresses,proto3" json:"number_of_ip_addresses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SubnetArgs) Reset() {
	*x = SubnetArgs{}
	mi := &file_proto_templates_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetArgs) ProtoMessage() {}

func (x *SubnetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetArgs.ProtoReflect.Descriptor instead.
func (*SubnetArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{5}
}

func (x *SubnetArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubnetArgs) GetNumberOfIpAddresses() int32 {
	if x != nil {
		return x.NumberOfIpAddresses
	}
	return 0
}

type SubnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IpsLeft       int32                  `protobuf:"varint,3,opt,name=ips_left,json=ipsLeft,proto3" json:"ips_left,omitempty"` // number of IP addresses left to consume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetResponse) Reset() {
	*x = SubnetResponse{}
	mi := &file_proto_templates_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetResponse) ProtoMessage() {}

func (x *SubnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetResponse.ProtoReflect.Descriptor instead.
func (*SubnetResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{6}
}

func (x *SubnetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubnetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubnetResponse) GetIpsLeft() int32 {
	if x != nil {
		return x.IpsLeft
	}
	return 0
}

type IpamPoolPrefixAllocation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IpamPoolResourceId  string                 `protobuf:"bytes,1,opt,name=ipam_pool_resource_id,json=ipamPoolResourceId,proto3" json:"ipam_pool_resource_id,omitempty"`
	NumberOfIpAddresses int32                  `protobuf:"varint,2,opt,name=number_of_ip_addresses,json=numberOfIpAddresses,proto3" json:"number_of_ip_addresses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IpamPoolPrefixAllocation) Reset() {
	*x = IpamPoolPrefixAllocation{}
	mi := &file_proto_templates_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpamPoolPrefixAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpamPoolPrefixAllocation) ProtoMessage() {}

func (x *IpamPoolPrefixAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpamPoolPrefixAllocation.ProtoReflect.Descriptor instead.
func (*IpamPoolPrefixAllocation) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{7}
}

func (x *IpamPoolPrefixAllocation) GetIpamPoolResourceId() string {
	if x != nil {
		return x.IpamPoolResourceId
	}
	return ""
}

func (x *IpamPoolPrefixAllocation) GetNumberOfIpAddresses() int32 {
	if x != nil {
		return x.NumberOfIpAddresses
	}
	return 0
}

var File_proto_templates_base_proto protoreflect.FileDescriptor

const file_proto_templates_base_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/templates/base.proto\x12\x0fproto.templates\x1a\x1cproto/templates/shared.proto\"\xa8\x02\n" +
	"\x04Base\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x01 \x01(\tR\tstackName\x12M\n" +
	"\x11provider_versions\x18\x02 \x03(\v2 .proto.templates.ProviderVersionR\x10providerVersions\x12?\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\x0e2 .proto.templates.TemplateOptionsR\tdependsOn\x126\n" +
	"\arequest\x18\x04 \x01(\v2\x1c.proto.templates.BaseRequestR\arequest\x129\n" +
	"\bresponse\x18\x05 \x01(\v2\x1d.proto.templates.BaseResponseR\bresponse\"\xe2\x01\n" +
	"\vBaseRequest\x12E\n" +
	"\x0edefault_params\x18\x01 \x01(\v2\x1e.proto.templates.DefaultParamsR\rdefaultParams\x12E\n" +
	"\fsubscription\x18\x02 \x01(\v2!.proto.templates.SubscriptionArgsR\fsubscription\x12E\n" +
	"\x0fvirtual_network\x18\x03 \x01(\v2\x1c.proto.templates.NetworkArgsR\x0evirtualNetwork\"\x8b\x01\n" +
	"\fBaseResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\avnet_id\x18\x02 \x01(\tR\x06vnetId\x129\n" +
	"\asubnets\x18\x03 \x03(\v2\x1f.proto.templates.SubnetResponseR\asubnets\"\x90\x01\n" +
	"\x10SubscriptionArgs\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12#\n" +
	"\rbilling_scope\x18\x02 \x01(\tR\fbillingScope\x12.\n" +
	"\x13management_group_id\x18\x03 \x01(\tR\x11managementGroupId\"\xb0\x01\n" +
	"\vNetworkArgs\x12j\n" +
	"\x1cipam_pool_prefix_allocations\x18\x01 \x01(\v2).proto.templates.IpamPoolPrefixAllocationR\x19ipamPoolPrefixAllocations\x125\n" +
	"\asubnets\x18\x02 \x03(\v2\x1b.proto.templates.SubnetArgsR\asubnets\"U\n" +
	"\n" +
	"SubnetArgs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x16number_of_ip_addresses\x18\x02 \x01(\x05R\x13numberOfIpAddresses\"O\n" +
	"\x0eSubnetResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\bips_left\x18\x03 \x01(\x05R\aipsLeft\"\x82\x01\n" +
	"\x18IpamPoolPrefixAllocation\x121\n" +
	"\x15ipam_pool_resource_id\x18\x01 \x01(\tR\x12ipamPoolResourceId\x123\n" +
	"\x16number_of_ip_addresses\x18\x02 \x01(\x05R\x13numberOfIpAddressesB>Z<github.com/htemuri/azure-pulumi-service-broker/pkg/templatesb\x06proto3"

var (
	file_proto_templates_base_proto_rawDescOnce sync.Once
	file_proto_templates_base_proto_rawDescData []byte
)

func file_proto_templates_base_proto_rawDescGZIP() []byte {
	file_proto_templates_base_proto_rawDescOnce.Do(func() {
		file_proto_templates_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_templates_base_proto_rawDesc), len(file_proto_templates_base_proto_rawDesc)))
	})
	return file_proto_templates_base_proto_rawDescData
}

var file_proto_templates_base_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_templates_base_proto_goTypes = []any{
	(*Base)(nil),                     // 0: proto.templates.Base
	(*BaseRequest)(nil),              // 1: proto.templates.BaseRequest
	(*BaseResponse)(nil),             // 2: proto.templates.BaseResponse
	(*SubscriptionArgs)(nil),         // 3: proto.templates.SubscriptionArgs
	(*NetworkArgs)(nil),              // 4: proto.templates.NetworkArgs
	(*SubnetArgs)(nil),               // 5: proto.templates.SubnetArgs
	(*SubnetResponse)(nil),           // 6: proto.templates.SubnetResponse
	(*IpamPoolPrefixAllocation)(nil), // 7: proto.templates.IpamPoolPrefixAllocation
	(*ProviderVersion)(nil),          // 8: proto.templates.ProviderVersion
	(TemplateOptions)(0),             // 9: proto.templates.TemplateOptions
	(*DefaultParams)(nil),            // 10: proto.templates.DefaultParams
}
var file_proto_templates_base_proto_depIdxs = []int32{
	8,  // 0: proto.templates.Base.provider_versions:type_name -> proto.templates.ProviderVersion
	9,  // 1: proto.templates.Base.depends_on:type_name -> proto.templates.TemplateOptions
	1,  // 2: proto.templates.Base.request:type_name -> proto.templates.BaseRequest
	2,  // 3: proto.templates.Base.response:type_name -> proto.templates.BaseResponse
	10, // 4: proto.templates.BaseRequest.default_params:type_name -> proto.templates.DefaultParams
	3,  // 5: proto.templates.BaseRequest.subscription:type_name -> proto.templates.SubscriptionArgs
	4,  // 6: proto.templates.BaseRequest.virtual_network:type_name -> proto.templates.NetworkArgs
	6,  // 7: proto.templates.BaseResponse.subnets:type_name -> proto.templates.SubnetResponse
	7,  // 8: proto.templates.NetworkArgs.ipam_pool_prefix_allocations:type_name -> proto.templates.IpamPoolPrefixAllocation
	5,  // 9: proto.templates.NetworkArgs.subnets:type_name -> proto.templates.SubnetArgs
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_templates_base_proto_init() }
func file_proto_templates_base_proto_init() {
	if File_proto_templates_base_proto != nil {
		return
	}
	file_proto_templates_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_templates_base_proto_rawDesc), len(file_proto_templates_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_base_proto_goTypes,
		DependencyIndexes: file_proto_templates_base_proto_depIdxs,
		MessageInfos:      file_proto_templates_base_proto_msgTypes,
	}.Build()
	File_proto_templates_base_proto = out.File
	file_proto_templates_base_proto_goTypes = nil
	file_proto_templates_base_proto_depIdxs = nil
}
