// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/templates/base.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stack creating/selecting subscription and networking
type Base struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultParams  *DefaultParams    `protobuf:"bytes,1,opt,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty"`
	Subscription   *SubscriptionArgs `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	VirtualNetwork *NetworkArgs      `protobuf:"bytes,3,opt,name=virtual_network,json=virtualNetwork,proto3" json:"virtual_network,omitempty"`
}

func (x *Base) Reset() {
	*x = Base{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetDefaultParams() *DefaultParams {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *Base) GetSubscription() *SubscriptionArgs {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Base) GetVirtualNetwork() *NetworkArgs {
	if x != nil {
		return x.VirtualNetwork
	}
	return nil
}

type SubscriptionArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptionId    string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // if not set, create a subscription using the env and project name in the format of "[{Environment}] Client Project: {ProjectName}"
	BillingScope      string `protobuf:"bytes,2,opt,name=billing_scope,json=billingScope,proto3" json:"billing_scope,omitempty"`
	ManagementGroupId string `protobuf:"bytes,3,opt,name=management_group_id,json=managementGroupId,proto3" json:"management_group_id,omitempty"`
}

func (x *SubscriptionArgs) Reset() {
	*x = SubscriptionArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionArgs) ProtoMessage() {}

func (x *SubscriptionArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionArgs.ProtoReflect.Descriptor instead.
func (*SubscriptionArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionArgs) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionArgs) GetBillingScope() string {
	if x != nil {
		return x.BillingScope
	}
	return ""
}

func (x *SubscriptionArgs) GetManagementGroupId() string {
	if x != nil {
		return x.ManagementGroupId
	}
	return ""
}

type NetworkArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpamPoolPrefixAllocations *IpamPoolPrefixAllocation `protobuf:"bytes,1,opt,name=ipam_pool_prefix_allocations,json=ipamPoolPrefixAllocations,proto3" json:"ipam_pool_prefix_allocations,omitempty"` // required (will error if not set)
	Subnets                   []*SubnetArgs             `protobuf:"bytes,2,rep,name=subnets,proto3" json:"subnets,omitempty"`
}

func (x *NetworkArgs) Reset() {
	*x = NetworkArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkArgs) ProtoMessage() {}

func (x *NetworkArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkArgs.ProtoReflect.Descriptor instead.
func (*NetworkArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkArgs) GetIpamPoolPrefixAllocations() *IpamPoolPrefixAllocation {
	if x != nil {
		return x.IpamPoolPrefixAllocations
	}
	return nil
}

func (x *NetworkArgs) GetSubnets() []*SubnetArgs {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type SubnetArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfIpAddresses int32  `protobuf:"varint,2,opt,name=number_of_ip_addresses,json=numberOfIpAddresses,proto3" json:"number_of_ip_addresses,omitempty"`
}

func (x *SubnetArgs) Reset() {
	*x = SubnetArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubnetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetArgs) ProtoMessage() {}

func (x *SubnetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetArgs.ProtoReflect.Descriptor instead.
func (*SubnetArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{3}
}

func (x *SubnetArgs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubnetArgs) GetNumberOfIpAddresses() int32 {
	if x != nil {
		return x.NumberOfIpAddresses
	}
	return 0
}

type IpamPoolPrefixAllocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpamPoolResourceId  string `protobuf:"bytes,1,opt,name=ipam_pool_resource_id,json=ipamPoolResourceId,proto3" json:"ipam_pool_resource_id,omitempty"`
	NumberOfIpAddresses int32  `protobuf:"varint,2,opt,name=number_of_ip_addresses,json=numberOfIpAddresses,proto3" json:"number_of_ip_addresses,omitempty"`
}

func (x *IpamPoolPrefixAllocation) Reset() {
	*x = IpamPoolPrefixAllocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpamPoolPrefixAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpamPoolPrefixAllocation) ProtoMessage() {}

func (x *IpamPoolPrefixAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpamPoolPrefixAllocation.ProtoReflect.Descriptor instead.
func (*IpamPoolPrefixAllocation) Descriptor() ([]byte, []int) {
	return file_proto_templates_base_proto_rawDescGZIP(), []int{4}
}

func (x *IpamPoolPrefixAllocation) GetIpamPoolResourceId() string {
	if x != nil {
		return x.IpamPoolResourceId
	}
	return ""
}

func (x *IpamPoolPrefixAllocation) GetNumberOfIpAddresses() int32 {
	if x != nil {
		return x.NumberOfIpAddresses
	}
	return 0
}

var File_proto_templates_base_proto protoreflect.FileDescriptor

var file_proto_templates_base_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x1c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x04,
	0x42, 0x61, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0d, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x45, 0x0a, 0x0c, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x72, 0x67, 0x73, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x0f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x52, 0x0e, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x13,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0xb0, 0x01, 0x0a,
	0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x6a, 0x0a, 0x1c,
	0x69, 0x70, 0x61, 0x6d, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x2e, 0x49, 0x70, 0x61, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x19, 0x69,
	0x70, 0x61, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6e,
	0x65, 0x74, 0x41, 0x72, 0x67, 0x73, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x22,
	0x55, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x33, 0x0a, 0x16, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x69,
	0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x13, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x49, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x49, 0x70, 0x61, 0x6d, 0x50,
	0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x15, 0x69, 0x70, 0x61, 0x6d, 0x5f, 0x70, 0x6f, 0x6f, 0x6c,
	0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x69, 0x70, 0x61, 0x6d, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x16, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x5f, 0x6f, 0x66, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66,
	0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74, 0x65, 0x6d, 0x75, 0x72,
	0x69, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_templates_base_proto_rawDescOnce sync.Once
	file_proto_templates_base_proto_rawDescData = file_proto_templates_base_proto_rawDesc
)

func file_proto_templates_base_proto_rawDescGZIP() []byte {
	file_proto_templates_base_proto_rawDescOnce.Do(func() {
		file_proto_templates_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_templates_base_proto_rawDescData)
	})
	return file_proto_templates_base_proto_rawDescData
}

var file_proto_templates_base_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_templates_base_proto_goTypes = []interface{}{
	(*Base)(nil),                     // 0: proto.templates.Base
	(*SubscriptionArgs)(nil),         // 1: proto.templates.SubscriptionArgs
	(*NetworkArgs)(nil),              // 2: proto.templates.NetworkArgs
	(*SubnetArgs)(nil),               // 3: proto.templates.SubnetArgs
	(*IpamPoolPrefixAllocation)(nil), // 4: proto.templates.IpamPoolPrefixAllocation
	(*DefaultParams)(nil),            // 5: proto.templates.DefaultParams
}
var file_proto_templates_base_proto_depIdxs = []int32{
	5, // 0: proto.templates.Base.default_params:type_name -> proto.templates.DefaultParams
	1, // 1: proto.templates.Base.subscription:type_name -> proto.templates.SubscriptionArgs
	2, // 2: proto.templates.Base.virtual_network:type_name -> proto.templates.NetworkArgs
	4, // 3: proto.templates.NetworkArgs.ipam_pool_prefix_allocations:type_name -> proto.templates.IpamPoolPrefixAllocation
	3, // 4: proto.templates.NetworkArgs.subnets:type_name -> proto.templates.SubnetArgs
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_templates_base_proto_init() }
func file_proto_templates_base_proto_init() {
	if File_proto_templates_base_proto != nil {
		return
	}
	file_proto_templates_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_templates_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubnetArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpamPoolPrefixAllocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_templates_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_base_proto_goTypes,
		DependencyIndexes: file_proto_templates_base_proto_depIdxs,
		MessageInfos:      file_proto_templates_base_proto_msgTypes,
	}.Build()
	File_proto_templates_base_proto = out.File
	file_proto_templates_base_proto_rawDesc = nil
	file_proto_templates_base_proto_goTypes = nil
	file_proto_templates_base_proto_depIdxs = nil
}
