// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/templates/security.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// stack for akvs and other resource types that are security related ...
type Security struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultParams *DefaultParams `protobuf:"bytes,1,opt,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty"`
	KeyVault      *KeyVaultArgs  `protobuf:"bytes,2,opt,name=key_vault,json=keyVault,proto3" json:"key_vault,omitempty"`
}

func (x *Security) Reset() {
	*x = Security{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_security_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{0}
}

func (x *Security) GetDefaultParams() *DefaultParams {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *Security) GetKeyVault() *KeyVaultArgs {
	if x != nil {
		return x.KeyVault
	}
	return nil
}

type KeyVaultArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disabled        *bool                `protobuf:"varint,1,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"` // enabled by default
	NetworkSettings *ResourceNetworkArgs `protobuf:"bytes,2,opt,name=network_settings,json=networkSettings,proto3" json:"network_settings,omitempty"`
}

func (x *KeyVaultArgs) Reset() {
	*x = KeyVaultArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_security_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyVaultArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVaultArgs) ProtoMessage() {}

func (x *KeyVaultArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVaultArgs.ProtoReflect.Descriptor instead.
func (*KeyVaultArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{1}
}

func (x *KeyVaultArgs) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *KeyVaultArgs) GetNetworkSettings() *ResourceNetworkArgs {
	if x != nil {
		return x.NetworkSettings
	}
	return nil
}

var File_proto_templates_security_proto protoreflect.FileDescriptor

var file_proto_templates_security_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8d, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x0e,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x22,
	0x8d, 0x01, 0x0a, 0x0c, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x1f, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x4f, 0x0a, 0x10, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42,
	0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74,
	0x65, 0x6d, 0x75, 0x72, 0x69, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75,
	0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_templates_security_proto_rawDescOnce sync.Once
	file_proto_templates_security_proto_rawDescData = file_proto_templates_security_proto_rawDesc
)

func file_proto_templates_security_proto_rawDescGZIP() []byte {
	file_proto_templates_security_proto_rawDescOnce.Do(func() {
		file_proto_templates_security_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_templates_security_proto_rawDescData)
	})
	return file_proto_templates_security_proto_rawDescData
}

var file_proto_templates_security_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_templates_security_proto_goTypes = []interface{}{
	(*Security)(nil),            // 0: proto.templates.Security
	(*KeyVaultArgs)(nil),        // 1: proto.templates.KeyVaultArgs
	(*DefaultParams)(nil),       // 2: proto.templates.DefaultParams
	(*ResourceNetworkArgs)(nil), // 3: proto.templates.ResourceNetworkArgs
}
var file_proto_templates_security_proto_depIdxs = []int32{
	2, // 0: proto.templates.Security.default_params:type_name -> proto.templates.DefaultParams
	1, // 1: proto.templates.Security.key_vault:type_name -> proto.templates.KeyVaultArgs
	3, // 2: proto.templates.KeyVaultArgs.network_settings:type_name -> proto.templates.ResourceNetworkArgs
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_templates_security_proto_init() }
func file_proto_templates_security_proto_init() {
	if File_proto_templates_security_proto != nil {
		return
	}
	file_proto_templates_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_templates_security_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Security); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_security_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyVaultArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_templates_security_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_templates_security_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_security_proto_goTypes,
		DependencyIndexes: file_proto_templates_security_proto_depIdxs,
		MessageInfos:      file_proto_templates_security_proto_msgTypes,
	}.Build()
	File_proto_templates_security_proto = out.File
	file_proto_templates_security_proto_rawDesc = nil
	file_proto_templates_security_proto_goTypes = nil
	file_proto_templates_security_proto_depIdxs = nil
}
