// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/templates/security.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// stack for akvs and other resource types that are security related ...
type Security struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StackName        string                 `protobuf:"bytes,1,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ProviderVersions []*ProviderVersion     `protobuf:"bytes,2,rep,name=provider_versions,json=providerVersions,proto3" json:"provider_versions,omitempty"`
	DependsOn        []TemplateOptions      `protobuf:"varint,3,rep,packed,name=depends_on,json=dependsOn,proto3,enum=proto.templates.TemplateOptions" json:"depends_on,omitempty"`
	Request          *SecurityRequest       `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response         *SecurityResponse      `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_proto_templates_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{0}
}

func (x *Security) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *Security) GetProviderVersions() []*ProviderVersion {
	if x != nil {
		return x.ProviderVersions
	}
	return nil
}

func (x *Security) GetDependsOn() []TemplateOptions {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Security) GetRequest() *SecurityRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Security) GetResponse() *SecurityResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type SecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultParams *DefaultParams         `protobuf:"bytes,1,opt,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty"`
	KeyVault      *KeyVaultArgs          `protobuf:"bytes,2,opt,name=key_vault,json=keyVault,proto3" json:"key_vault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequest) Reset() {
	*x = SecurityRequest{}
	mi := &file_proto_templates_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequest) ProtoMessage() {}

func (x *SecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequest.ProtoReflect.Descriptor instead.
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityRequest) GetDefaultParams() *DefaultParams {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *SecurityRequest) GetKeyVault() *KeyVaultArgs {
	if x != nil {
		return x.KeyVault
	}
	return nil
}

type SecurityResponse struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	ResourceGroupName string                     `protobuf:"bytes,1,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ResourceGroupId   string                     `protobuf:"bytes,2,opt,name=resource_group_id,json=resourceGroupId,proto3" json:"resource_group_id,omitempty"`
	KeyVaultId        string                     `protobuf:"bytes,3,opt,name=key_vault_id,json=keyVaultId,proto3" json:"key_vault_id,omitempty"`
	KeyVaultUri       string                     `protobuf:"bytes,4,opt,name=key_vault_uri,json=keyVaultUri,proto3" json:"key_vault_uri,omitempty"`
	PrivateEndpoints  []*PrivateEndpointResponse `protobuf:"bytes,5,rep,name=private_endpoints,json=privateEndpoints,proto3" json:"private_endpoints,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_proto_templates_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityResponse) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

func (x *SecurityResponse) GetResourceGroupId() string {
	if x != nil {
		return x.ResourceGroupId
	}
	return ""
}

func (x *SecurityResponse) GetKeyVaultId() string {
	if x != nil {
		return x.KeyVaultId
	}
	return ""
}

func (x *SecurityResponse) GetKeyVaultUri() string {
	if x != nil {
		return x.KeyVaultUri
	}
	return ""
}

func (x *SecurityResponse) GetPrivateEndpoints() []*PrivateEndpointResponse {
	if x != nil {
		return x.PrivateEndpoints
	}
	return nil
}

type KeyVaultArgs struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Disabled        bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`                                     // enabled by default
	NetworkSettings *ResourceNetworkArgs   `protobuf:"bytes,2,opt,name=network_settings,json=networkSettings,proto3" json:"network_settings,omitempty"` // default public network disabled with no private endpoints
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KeyVaultArgs) Reset() {
	*x = KeyVaultArgs{}
	mi := &file_proto_templates_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVaultArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVaultArgs) ProtoMessage() {}

func (x *KeyVaultArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVaultArgs.ProtoReflect.Descriptor instead.
func (*KeyVaultArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_security_proto_rawDescGZIP(), []int{3}
}

func (x *KeyVaultArgs) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *KeyVaultArgs) GetNetworkSettings() *ResourceNetworkArgs {
	if x != nil {
		return x.NetworkSettings
	}
	return nil
}

var File_proto_templates_security_proto protoreflect.FileDescriptor

const file_proto_templates_security_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/templates/security.proto\x12\x0fproto.templates\x1a\x1cproto/templates/shared.proto\"\xb4\x02\n" +
	"\bSecurity\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x01 \x01(\tR\tstackName\x12M\n" +
	"\x11provider_versions\x18\x02 \x03(\v2 .proto.templates.ProviderVersionR\x10providerVersions\x12?\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\x0e2 .proto.templates.TemplateOptionsR\tdependsOn\x12:\n" +
	"\arequest\x18\x04 \x01(\v2 .proto.templates.SecurityRequestR\arequest\x12=\n" +
	"\bresponse\x18\x05 \x01(\v2!.proto.templates.SecurityResponseR\bresponse\"\x94\x01\n" +
	"\x0fSecurityRequest\x12E\n" +
	"\x0edefault_params\x18\x01 \x01(\v2\x1e.proto.templates.DefaultParamsR\rdefaultParams\x12:\n" +
	"\tkey_vault\x18\x02 \x01(\v2\x1d.proto.templates.KeyVaultArgsR\bkeyVault\"\x8b\x02\n" +
	"\x10SecurityResponse\x12.\n" +
	"\x13resource_group_name\x18\x01 \x01(\tR\x11resourceGroupName\x12*\n" +
	"\x11resource_group_id\x18\x02 \x01(\tR\x0fresourceGroupId\x12 \n" +
	"\fkey_vault_id\x18\x03 \x01(\tR\n" +
	"keyVaultId\x12\"\n" +
	"\rkey_vault_uri\x18\x04 \x01(\tR\vkeyVaultUri\x12U\n" +
	"\x11private_endpoints\x18\x05 \x03(\v2(.proto.templates.PrivateEndpointResponseR\x10privateEndpoints\"{\n" +
	"\fKeyVaultArgs\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12O\n" +
	"\x10network_settings\x18\x02 \x01(\v2$.proto.templates.ResourceNetworkArgsR\x0fnetworkSettingsB>Z<github.com/htemuri/azure-pulumi-service-broker/pkg/templatesb\x06proto3"

var (
	file_proto_templates_security_proto_rawDescOnce sync.Once
	file_proto_templates_security_proto_rawDescData []byte
)

func file_proto_templates_security_proto_rawDescGZIP() []byte {
	file_proto_templates_security_proto_rawDescOnce.Do(func() {
		file_proto_templates_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_templates_security_proto_rawDesc), len(file_proto_templates_security_proto_rawDesc)))
	})
	return file_proto_templates_security_proto_rawDescData
}

var file_proto_templates_security_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_templates_security_proto_goTypes = []any{
	(*Security)(nil),                // 0: proto.templates.Security
	(*SecurityRequest)(nil),         // 1: proto.templates.SecurityRequest
	(*SecurityResponse)(nil),        // 2: proto.templates.SecurityResponse
	(*KeyVaultArgs)(nil),            // 3: proto.templates.KeyVaultArgs
	(*ProviderVersion)(nil),         // 4: proto.templates.ProviderVersion
	(TemplateOptions)(0),            // 5: proto.templates.TemplateOptions
	(*DefaultParams)(nil),           // 6: proto.templates.DefaultParams
	(*PrivateEndpointResponse)(nil), // 7: proto.templates.PrivateEndpointResponse
	(*ResourceNetworkArgs)(nil),     // 8: proto.templates.ResourceNetworkArgs
}
var file_proto_templates_security_proto_depIdxs = []int32{
	4, // 0: proto.templates.Security.provider_versions:type_name -> proto.templates.ProviderVersion
	5, // 1: proto.templates.Security.depends_on:type_name -> proto.templates.TemplateOptions
	1, // 2: proto.templates.Security.request:type_name -> proto.templates.SecurityRequest
	2, // 3: proto.templates.Security.response:type_name -> proto.templates.SecurityResponse
	6, // 4: proto.templates.SecurityRequest.default_params:type_name -> proto.templates.DefaultParams
	3, // 5: proto.templates.SecurityRequest.key_vault:type_name -> proto.templates.KeyVaultArgs
	7, // 6: proto.templates.SecurityResponse.private_endpoints:type_name -> proto.templates.PrivateEndpointResponse
	8, // 7: proto.templates.KeyVaultArgs.network_settings:type_name -> proto.templates.ResourceNetworkArgs
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_templates_security_proto_init() }
func file_proto_templates_security_proto_init() {
	if File_proto_templates_security_proto != nil {
		return
	}
	file_proto_templates_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_templates_security_proto_rawDesc), len(file_proto_templates_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_security_proto_goTypes,
		DependencyIndexes: file_proto_templates_security_proto_depIdxs,
		MessageInfos:      file_proto_templates_security_proto_msgTypes,
	}.Build()
	File_proto_templates_security_proto = out.File
	file_proto_templates_security_proto_goTypes = nil
	file_proto_templates_security_proto_depIdxs = nil
}
