// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/templates/shared.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateOptions int32

const (
	TemplateOptions_TEMPLATE_OPTIONS_UNSPECIFIED TemplateOptions = 0
	TemplateOptions_TEMPLATE_OPTIONS_BASE        TemplateOptions = 1
	TemplateOptions_TEMPLATE_OPTIONS_SECURITY    TemplateOptions = 2
	TemplateOptions_TEMPLATE_OPTIONS_STORAGE     TemplateOptions = 3
)

// Enum value maps for TemplateOptions.
var (
	TemplateOptions_name = map[int32]string{
		0: "TEMPLATE_OPTIONS_UNSPECIFIED",
		1: "TEMPLATE_OPTIONS_BASE",
		2: "TEMPLATE_OPTIONS_SECURITY",
		3: "TEMPLATE_OPTIONS_STORAGE",
	}
	TemplateOptions_value = map[string]int32{
		"TEMPLATE_OPTIONS_UNSPECIFIED": 0,
		"TEMPLATE_OPTIONS_BASE":        1,
		"TEMPLATE_OPTIONS_SECURITY":    2,
		"TEMPLATE_OPTIONS_STORAGE":     3,
	}
)

func (x TemplateOptions) Enum() *TemplateOptions {
	p := new(TemplateOptions)
	*p = x
	return p
}

func (x TemplateOptions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateOptions) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[0].Descriptor()
}

func (TemplateOptions) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[0]
}

func (x TemplateOptions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateOptions.Descriptor instead.
func (TemplateOptions) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_ERROR       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_ERROR":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{1}
}

type Environment int32

const (
	Environment_ENVIRONMENT_UNSPECIFIED Environment = 0
	Environment_ENVIRONMENT_DEV         Environment = 1
	Environment_ENVIRONMENT_TST         Environment = 2
	Environment_ENVIRONMENT_STG         Environment = 3
	Environment_ENVIRONMENT_PRD         Environment = 4
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ENVIRONMENT_UNSPECIFIED",
		1: "ENVIRONMENT_DEV",
		2: "ENVIRONMENT_TST",
		3: "ENVIRONMENT_STG",
		4: "ENVIRONMENT_PRD",
	}
	Environment_value = map[string]int32{
		"ENVIRONMENT_UNSPECIFIED": 0,
		"ENVIRONMENT_DEV":         1,
		"ENVIRONMENT_TST":         2,
		"ENVIRONMENT_STG":         3,
		"ENVIRONMENT_PRD":         4,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[2].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[2]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{2}
}

type Region int32

const (
	Region_REGION_UNSPECIFIED Region = 0
	Region_REGION_EASTUS      Region = 1
	Region_REGION_EASTUS2     Region = 2
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0: "REGION_UNSPECIFIED",
		1: "REGION_EASTUS",
		2: "REGION_EASTUS2",
	}
	Region_value = map[string]int32{
		"REGION_UNSPECIFIED": 0,
		"REGION_EASTUS":      1,
		"REGION_EASTUS2":     2,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[3].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[3]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{3}
}

type DefaultParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectName              string                        `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Environment              Environment                   `protobuf:"varint,2,opt,name=environment,proto3,enum=proto.templates.Environment" json:"environment,omitempty"`
	Region                   Region                        `protobuf:"varint,3,opt,name=region,proto3,enum=proto.templates.Region" json:"region,omitempty"`                                          // if unspecified, will default to eastus
	PulumiProviderCredential *PulumiProviderCredentialArgs `protobuf:"bytes,4,opt,name=pulumi_provider_credential,json=pulumiProviderCredential,proto3" json:"pulumi_provider_credential,omitempty"` // repeated TemplateOptions depends_on = 8;
}

func (x *DefaultParams) Reset() {
	*x = DefaultParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_shared_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultParams) ProtoMessage() {}

func (x *DefaultParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultParams.ProtoReflect.Descriptor instead.
func (*DefaultParams) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultParams) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DefaultParams) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENVIRONMENT_UNSPECIFIED
}

func (x *DefaultParams) GetRegion() Region {
	if x != nil {
		return x.Region
	}
	return Region_REGION_UNSPECIFIED
}

func (x *DefaultParams) GetPulumiProviderCredential() *PulumiProviderCredentialArgs {
	if x != nil {
		return x.PulumiProviderCredential
	}
	return nil
}

type PulumiProviderCredentialArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId     string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
}

func (x *PulumiProviderCredentialArgs) Reset() {
	*x = PulumiProviderCredentialArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_shared_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PulumiProviderCredentialArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulumiProviderCredentialArgs) ProtoMessage() {}

func (x *PulumiProviderCredentialArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulumiProviderCredentialArgs.ProtoReflect.Descriptor instead.
func (*PulumiProviderCredentialArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{1}
}

func (x *PulumiProviderCredentialArgs) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PulumiProviderCredentialArgs) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PulumiProviderCredentialArgs) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ProviderVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Version      string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ProviderVersion) Reset() {
	*x = ProviderVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_shared_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion) ProtoMessage() {}

func (x *ProviderVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion.ProtoReflect.Descriptor instead.
func (*ProviderVersion) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderVersion) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResourceNetworkArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicNetworkEnabled bool                 `protobuf:"varint,1,opt,name=public_network_enabled,json=publicNetworkEnabled,proto3" json:"public_network_enabled,omitempty"` // default disabled
	PrivateEndpoint      *PrivateEndpointArgs `protobuf:"bytes,2,opt,name=private_endpoint,json=privateEndpoint,proto3" json:"private_endpoint,omitempty"`
}

func (x *ResourceNetworkArgs) Reset() {
	*x = ResourceNetworkArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_shared_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceNetworkArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceNetworkArgs) ProtoMessage() {}

func (x *ResourceNetworkArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceNetworkArgs.ProtoReflect.Descriptor instead.
func (*ResourceNetworkArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceNetworkArgs) GetPublicNetworkEnabled() bool {
	if x != nil {
		return x.PublicNetworkEnabled
	}
	return false
}

func (x *ResourceNetworkArgs) GetPrivateEndpoint() *PrivateEndpointArgs {
	if x != nil {
		return x.PrivateEndpoint
	}
	return nil
}

type PrivateEndpointArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled      bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                        // default disabled
	SubnetId     *string  `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3,oneof" json:"subnet_id,omitempty"` // if not specified, then use default subnet id from base network vnet
	SubResources []string `protobuf:"bytes,3,rep,name=sub_resources,json=subResources,proto3" json:"sub_resources,omitempty"`
}

func (x *PrivateEndpointArgs) Reset() {
	*x = PrivateEndpointArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_shared_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateEndpointArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateEndpointArgs) ProtoMessage() {}

func (x *PrivateEndpointArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateEndpointArgs.ProtoReflect.Descriptor instead.
func (*PrivateEndpointArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{4}
}

func (x *PrivateEndpointArgs) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PrivateEndpointArgs) GetSubnetId() string {
	if x != nil && x.SubnetId != nil {
		return *x.SubnetId
	}
	return ""
}

func (x *PrivateEndpointArgs) GetSubResources() []string {
	if x != nil {
		return x.SubResources
	}
	return nil
}

var File_proto_templates_shared_proto protoreflect.FileDescriptor

var file_proto_templates_shared_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x90, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x6b, 0x0a, 0x1a, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x5f,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x50, 0x75, 0x6c, 0x75,
	0x6d, 0x69, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x41, 0x72, 0x67, 0x73, 0x52, 0x18, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x22, 0x7d, 0x0a, 0x1c, 0x50, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x50, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x12, 0x4f, 0x0a, 0x10, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x0f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x75, 0x62, 0x6e, 0x65,
	0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73,
	0x75, 0x62, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x2a, 0x8b, 0x01, 0x0a, 0x0f, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a,
	0x1c, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x19, 0x0a, 0x15, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x53, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x54, 0x45,
	0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x53,
	0x45, 0x43, 0x55, 0x52, 0x49, 0x54, 0x59, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x54, 0x45, 0x4d,
	0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x53, 0x54,
	0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x03, 0x2a, 0x46, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x2a,
	0x7e, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x17, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45,
	0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x56, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x54, 0x53, 0x54, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x56, 0x49, 0x52, 0x4f, 0x4e,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x47, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e,
	0x56, 0x49, 0x52, 0x4f, 0x4e, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x50, 0x52, 0x44, 0x10, 0x04, 0x2a,
	0x47, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x47,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x41, 0x53, 0x54,
	0x55, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x45,
	0x41, 0x53, 0x54, 0x55, 0x53, 0x32, 0x10, 0x02, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74, 0x65, 0x6d, 0x75, 0x72, 0x69, 0x2f, 0x61,
	0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_templates_shared_proto_rawDescOnce sync.Once
	file_proto_templates_shared_proto_rawDescData = file_proto_templates_shared_proto_rawDesc
)

func file_proto_templates_shared_proto_rawDescGZIP() []byte {
	file_proto_templates_shared_proto_rawDescOnce.Do(func() {
		file_proto_templates_shared_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_templates_shared_proto_rawDescData)
	})
	return file_proto_templates_shared_proto_rawDescData
}

var file_proto_templates_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_templates_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_templates_shared_proto_goTypes = []interface{}{
	(TemplateOptions)(0),                 // 0: proto.templates.TemplateOptions
	(Status)(0),                          // 1: proto.templates.Status
	(Environment)(0),                     // 2: proto.templates.Environment
	(Region)(0),                          // 3: proto.templates.Region
	(*DefaultParams)(nil),                // 4: proto.templates.DefaultParams
	(*PulumiProviderCredentialArgs)(nil), // 5: proto.templates.PulumiProviderCredentialArgs
	(*ProviderVersion)(nil),              // 6: proto.templates.ProviderVersion
	(*ResourceNetworkArgs)(nil),          // 7: proto.templates.ResourceNetworkArgs
	(*PrivateEndpointArgs)(nil),          // 8: proto.templates.PrivateEndpointArgs
}
var file_proto_templates_shared_proto_depIdxs = []int32{
	2, // 0: proto.templates.DefaultParams.environment:type_name -> proto.templates.Environment
	3, // 1: proto.templates.DefaultParams.region:type_name -> proto.templates.Region
	5, // 2: proto.templates.DefaultParams.pulumi_provider_credential:type_name -> proto.templates.PulumiProviderCredentialArgs
	8, // 3: proto.templates.ResourceNetworkArgs.private_endpoint:type_name -> proto.templates.PrivateEndpointArgs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_templates_shared_proto_init() }
func file_proto_templates_shared_proto_init() {
	if File_proto_templates_shared_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_templates_shared_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_shared_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PulumiProviderCredentialArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_shared_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_shared_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceNetworkArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_shared_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateEndpointArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_templates_shared_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_templates_shared_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_shared_proto_goTypes,
		DependencyIndexes: file_proto_templates_shared_proto_depIdxs,
		EnumInfos:         file_proto_templates_shared_proto_enumTypes,
		MessageInfos:      file_proto_templates_shared_proto_msgTypes,
	}.Build()
	File_proto_templates_shared_proto = out.File
	file_proto_templates_shared_proto_rawDesc = nil
	file_proto_templates_shared_proto_goTypes = nil
	file_proto_templates_shared_proto_depIdxs = nil
}
