// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/templates/shared.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateOptions int32

const (
	TemplateOptions_TEMPLATE_OPTIONS_UNSPECIFIED TemplateOptions = 0
	TemplateOptions_TEMPLATE_OPTIONS_BASE        TemplateOptions = 1
	TemplateOptions_TEMPLATE_OPTIONS_SECURITY    TemplateOptions = 2
	TemplateOptions_TEMPLATE_OPTIONS_STORAGE     TemplateOptions = 3
)

// Enum value maps for TemplateOptions.
var (
	TemplateOptions_name = map[int32]string{
		0: "TEMPLATE_OPTIONS_UNSPECIFIED",
		1: "TEMPLATE_OPTIONS_BASE",
		2: "TEMPLATE_OPTIONS_SECURITY",
		3: "TEMPLATE_OPTIONS_STORAGE",
	}
	TemplateOptions_value = map[string]int32{
		"TEMPLATE_OPTIONS_UNSPECIFIED": 0,
		"TEMPLATE_OPTIONS_BASE":        1,
		"TEMPLATE_OPTIONS_SECURITY":    2,
		"TEMPLATE_OPTIONS_STORAGE":     3,
	}
)

func (x TemplateOptions) Enum() *TemplateOptions {
	p := new(TemplateOptions)
	*p = x
	return p
}

func (x TemplateOptions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateOptions) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[0].Descriptor()
}

func (TemplateOptions) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[0]
}

func (x TemplateOptions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateOptions.Descriptor instead.
func (TemplateOptions) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_IN_PROGRESS Status = 1
	Status_STATUS_SUCCESS     Status = 2
	Status_STATUS_ERROR       Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IN_PROGRESS",
		2: "STATUS_SUCCESS",
		3: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IN_PROGRESS": 1,
		"STATUS_SUCCESS":     2,
		"STATUS_ERROR":       3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{1}
}

type Environment int32

const (
	Environment_ENVIRONMENT_UNSPECIFIED Environment = 0
	Environment_ENVIRONMENT_DEV         Environment = 1
	Environment_ENVIRONMENT_TST         Environment = 2
	Environment_ENVIRONMENT_STG         Environment = 3
	Environment_ENVIRONMENT_PRD         Environment = 4
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ENVIRONMENT_UNSPECIFIED",
		1: "ENVIRONMENT_DEV",
		2: "ENVIRONMENT_TST",
		3: "ENVIRONMENT_STG",
		4: "ENVIRONMENT_PRD",
	}
	Environment_value = map[string]int32{
		"ENVIRONMENT_UNSPECIFIED": 0,
		"ENVIRONMENT_DEV":         1,
		"ENVIRONMENT_TST":         2,
		"ENVIRONMENT_STG":         3,
		"ENVIRONMENT_PRD":         4,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[2].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[2]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{2}
}

type Region int32

const (
	Region_REGION_UNSPECIFIED Region = 0
	Region_REGION_EASTUS      Region = 1
	Region_REGION_EASTUS2     Region = 2
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0: "REGION_UNSPECIFIED",
		1: "REGION_EASTUS",
		2: "REGION_EASTUS2",
	}
	Region_value = map[string]int32{
		"REGION_UNSPECIFIED": 0,
		"REGION_EASTUS":      1,
		"REGION_EASTUS2":     2,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_shared_proto_enumTypes[3].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_proto_templates_shared_proto_enumTypes[3]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{3}
}

type DefaultParams struct {
	state                    protoimpl.MessageState        `protogen:"open.v1"`
	ProjectName              string                        `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Environment              Environment                   `protobuf:"varint,2,opt,name=environment,proto3,enum=proto.templates.Environment" json:"environment,omitempty"`
	Region                   Region                        `protobuf:"varint,3,opt,name=region,proto3,enum=proto.templates.Region" json:"region,omitempty"`                                          // if unspecified, will default to eastus
	PulumiProviderCredential *PulumiProviderCredentialArgs `protobuf:"bytes,4,opt,name=pulumi_provider_credential,json=pulumiProviderCredential,proto3" json:"pulumi_provider_credential,omitempty"` // this is the service principal used to execute the deployment in Azure
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DefaultParams) Reset() {
	*x = DefaultParams{}
	mi := &file_proto_templates_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultParams) ProtoMessage() {}

func (x *DefaultParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultParams.ProtoReflect.Descriptor instead.
func (*DefaultParams) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultParams) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *DefaultParams) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENVIRONMENT_UNSPECIFIED
}

func (x *DefaultParams) GetRegion() Region {
	if x != nil {
		return x.Region
	}
	return Region_REGION_UNSPECIFIED
}

func (x *DefaultParams) GetPulumiProviderCredential() *PulumiProviderCredentialArgs {
	if x != nil {
		return x.PulumiProviderCredential
	}
	return nil
}

type PulumiProviderCredentialArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulumiProviderCredentialArgs) Reset() {
	*x = PulumiProviderCredentialArgs{}
	mi := &file_proto_templates_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulumiProviderCredentialArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulumiProviderCredentialArgs) ProtoMessage() {}

func (x *PulumiProviderCredentialArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulumiProviderCredentialArgs.ProtoReflect.Descriptor instead.
func (*PulumiProviderCredentialArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{1}
}

func (x *PulumiProviderCredentialArgs) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PulumiProviderCredentialArgs) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PulumiProviderCredentialArgs) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ProviderVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderVersion) Reset() {
	*x = ProviderVersion{}
	mi := &file_proto_templates_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderVersion) ProtoMessage() {}

func (x *ProviderVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderVersion.ProtoReflect.Descriptor instead.
func (*ProviderVersion) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderVersion) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResourceNetworkArgs struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PublicNetworkEnabled bool                   `protobuf:"varint,1,opt,name=public_network_enabled,json=publicNetworkEnabled,proto3" json:"public_network_enabled,omitempty"` // default disabled
	PrivateEndpoint      *PrivateEndpointArgs   `protobuf:"bytes,2,opt,name=private_endpoint,json=privateEndpoint,proto3" json:"private_endpoint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceNetworkArgs) Reset() {
	*x = ResourceNetworkArgs{}
	mi := &file_proto_templates_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceNetworkArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceNetworkArgs) ProtoMessage() {}

func (x *ResourceNetworkArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceNetworkArgs.ProtoReflect.Descriptor instead.
func (*ResourceNetworkArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceNetworkArgs) GetPublicNetworkEnabled() bool {
	if x != nil {
		return x.PublicNetworkEnabled
	}
	return false
}

func (x *ResourceNetworkArgs) GetPrivateEndpoint() *PrivateEndpointArgs {
	if x != nil {
		return x.PrivateEndpoint
	}
	return nil
}

type PrivateEndpointArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                              // default disabled
	SubnetId      *string                `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3,oneof" json:"subnet_id,omitempty"`       // if not specified, then use default subnet id from base network vnet
	SubResources  []string               `protobuf:"bytes,3,rep,name=sub_resources,json=subResources,proto3" json:"sub_resources,omitempty"` // for ex: `vault` for keyvault; `blob`, `dfs`, `queue`, `file`, `table` for storage accounts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateEndpointArgs) Reset() {
	*x = PrivateEndpointArgs{}
	mi := &file_proto_templates_shared_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateEndpointArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateEndpointArgs) ProtoMessage() {}

func (x *PrivateEndpointArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateEndpointArgs.ProtoReflect.Descriptor instead.
func (*PrivateEndpointArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{4}
}

func (x *PrivateEndpointArgs) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PrivateEndpointArgs) GetSubnetId() string {
	if x != nil && x.SubnetId != nil {
		return *x.SubnetId
	}
	return ""
}

func (x *PrivateEndpointArgs) GetSubResources() []string {
	if x != nil {
		return x.SubResources
	}
	return nil
}

type PrivateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DnsZoneName   string                 `protobuf:"bytes,1,opt,name=dns_zone_name,json=dnsZoneName,proto3" json:"dns_zone_name,omitempty"`
	Fqdn          string                 `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateEndpointResponse) Reset() {
	*x = PrivateEndpointResponse{}
	mi := &file_proto_templates_shared_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateEndpointResponse) ProtoMessage() {}

func (x *PrivateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_shared_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateEndpointResponse.ProtoReflect.Descriptor instead.
func (*PrivateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_shared_proto_rawDescGZIP(), []int{5}
}

func (x *PrivateEndpointResponse) GetDnsZoneName() string {
	if x != nil {
		return x.DnsZoneName
	}
	return ""
}

func (x *PrivateEndpointResponse) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *PrivateEndpointResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

var File_proto_templates_shared_proto protoreflect.FileDescriptor

const file_proto_templates_shared_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/templates/shared.proto\x12\x0fproto.templates\"\x90\x02\n" +
	"\rDefaultParams\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12>\n" +
	"\venvironment\x18\x02 \x01(\x0e2\x1c.proto.templates.EnvironmentR\venvironment\x12/\n" +
	"\x06region\x18\x03 \x01(\x0e2\x17.proto.templates.RegionR\x06region\x12k\n" +
	"\x1apulumi_provider_credential\x18\x04 \x01(\v2-.proto.templates.PulumiProviderCredentialArgsR\x18pulumiProviderCredential\"}\n" +
	"\x1cPulumiProviderCredentialArgs\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"P\n" +
	"\x0fProviderVersion\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x9c\x01\n" +
	"\x13ResourceNetworkArgs\x124\n" +
	"\x16public_network_enabled\x18\x01 \x01(\bR\x14publicNetworkEnabled\x12O\n" +
	"\x10private_endpoint\x18\x02 \x01(\v2$.proto.templates.PrivateEndpointArgsR\x0fprivateEndpoint\"\x84\x01\n" +
	"\x13PrivateEndpointArgs\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12 \n" +
	"\tsubnet_id\x18\x02 \x01(\tH\x00R\bsubnetId\x88\x01\x01\x12#\n" +
	"\rsub_resources\x18\x03 \x03(\tR\fsubResourcesB\f\n" +
	"\n" +
	"_subnet_id\"p\n" +
	"\x17PrivateEndpointResponse\x12\"\n" +
	"\rdns_zone_name\x18\x01 \x01(\tR\vdnsZoneName\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress*\x8b\x01\n" +
	"\x0fTemplateOptions\x12 \n" +
	"\x1cTEMPLATE_OPTIONS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TEMPLATE_OPTIONS_BASE\x10\x01\x12\x1d\n" +
	"\x19TEMPLATE_OPTIONS_SECURITY\x10\x02\x12\x1c\n" +
	"\x18TEMPLATE_OPTIONS_STORAGE\x10\x03*^\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x03*~\n" +
	"\vEnvironment\x12\x1b\n" +
	"\x17ENVIRONMENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fENVIRONMENT_DEV\x10\x01\x12\x13\n" +
	"\x0fENVIRONMENT_TST\x10\x02\x12\x13\n" +
	"\x0fENVIRONMENT_STG\x10\x03\x12\x13\n" +
	"\x0fENVIRONMENT_PRD\x10\x04*G\n" +
	"\x06Region\x12\x16\n" +
	"\x12REGION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rREGION_EASTUS\x10\x01\x12\x12\n" +
	"\x0eREGION_EASTUS2\x10\x02B>Z<github.com/htemuri/azure-pulumi-service-broker/pkg/templatesb\x06proto3"

var (
	file_proto_templates_shared_proto_rawDescOnce sync.Once
	file_proto_templates_shared_proto_rawDescData []byte
)

func file_proto_templates_shared_proto_rawDescGZIP() []byte {
	file_proto_templates_shared_proto_rawDescOnce.Do(func() {
		file_proto_templates_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_templates_shared_proto_rawDesc), len(file_proto_templates_shared_proto_rawDesc)))
	})
	return file_proto_templates_shared_proto_rawDescData
}

var file_proto_templates_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_templates_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_templates_shared_proto_goTypes = []any{
	(TemplateOptions)(0),                 // 0: proto.templates.TemplateOptions
	(Status)(0),                          // 1: proto.templates.Status
	(Environment)(0),                     // 2: proto.templates.Environment
	(Region)(0),                          // 3: proto.templates.Region
	(*DefaultParams)(nil),                // 4: proto.templates.DefaultParams
	(*PulumiProviderCredentialArgs)(nil), // 5: proto.templates.PulumiProviderCredentialArgs
	(*ProviderVersion)(nil),              // 6: proto.templates.ProviderVersion
	(*ResourceNetworkArgs)(nil),          // 7: proto.templates.ResourceNetworkArgs
	(*PrivateEndpointArgs)(nil),          // 8: proto.templates.PrivateEndpointArgs
	(*PrivateEndpointResponse)(nil),      // 9: proto.templates.PrivateEndpointResponse
}
var file_proto_templates_shared_proto_depIdxs = []int32{
	2, // 0: proto.templates.DefaultParams.environment:type_name -> proto.templates.Environment
	3, // 1: proto.templates.DefaultParams.region:type_name -> proto.templates.Region
	5, // 2: proto.templates.DefaultParams.pulumi_provider_credential:type_name -> proto.templates.PulumiProviderCredentialArgs
	8, // 3: proto.templates.ResourceNetworkArgs.private_endpoint:type_name -> proto.templates.PrivateEndpointArgs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_templates_shared_proto_init() }
func file_proto_templates_shared_proto_init() {
	if File_proto_templates_shared_proto != nil {
		return
	}
	file_proto_templates_shared_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_templates_shared_proto_rawDesc), len(file_proto_templates_shared_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_shared_proto_goTypes,
		DependencyIndexes: file_proto_templates_shared_proto_depIdxs,
		EnumInfos:         file_proto_templates_shared_proto_enumTypes,
		MessageInfos:      file_proto_templates_shared_proto_msgTypes,
	}.Build()
	File_proto_templates_shared_proto = out.File
	file_proto_templates_shared_proto_goTypes = nil
	file_proto_templates_shared_proto_depIdxs = nil
}
