// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/templates/storage.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorAcctSKU int32

const (
	StorAcctSKU_STOR_ACCT_SKU_UNSPECIFIED     StorAcctSKU = 0
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_LRS    StorAcctSKU = 1  // Pay-as-you-go storage account HDD with locally redundant storage (LRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_ZRS    StorAcctSKU = 2  // Pay-as-you-go storage account HDD with zone redundant storage (ZRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_GRS    StorAcctSKU = 3  // Pay-as-you-go storage account HDD with geo redundant storage (GRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_GZRS   StorAcctSKU = 4  // Pay-as-you-go storage account HDD with geo-zone redundant storage (GZRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_RAGRS  StorAcctSKU = 5  // Pay-as-you-go storage account HDD with read-accessible geo redundant storage (RAGRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARD_RAGZRS StorAcctSKU = 6  // Pay-as-you-go storage account HDD with read-accessible geo-zone redundant storage (RAGZRS)
	StorAcctSKU_STOR_ACCT_SKU_PREMIUM_LRS     StorAcctSKU = 7  // Pay-as-you-go storage account SSD with locally redundant storage (LRS)
	StorAcctSKU_STOR_ACCT_SKU_PREMIUM_ZRS     StorAcctSKU = 8  // Pay-as-you-go storage account SSD with zone redundant storage (ZRS)
	StorAcctSKU_STOR_ACCT_SKU_STANDARDV2_LRS  StorAcctSKU = 9  // Provisioned v2 storage account HDD with locally redundant storage
	StorAcctSKU_STOR_ACCT_SKU_STANDARDV2_ZRS  StorAcctSKU = 10 // Provisioned v2 storage account HDD with zone redundant storage
	StorAcctSKU_STOR_ACCT_SKU_STANDARDV2_GRS  StorAcctSKU = 11 // Provisioned v2 storage account HDD with geo redundant storage.
	StorAcctSKU_STOR_ACCT_SKU_STANDARDV2_GZRS StorAcctSKU = 12 // Provisioned v2 storage account HDD with geo-zone redundant.
	StorAcctSKU_STOR_ACCT_SKU_PREMIUMV2_LRS   StorAcctSKU = 13 // Provisioned v2 storage account SSD with locally redundant storage.
	StorAcctSKU_STOR_ACCT_SKU_PREMIUMV2_ZRS   StorAcctSKU = 14 // Provisioned v2 storage account SSD with zone redundant storage.
)

// Enum value maps for StorAcctSKU.
var (
	StorAcctSKU_name = map[int32]string{
		0:  "STOR_ACCT_SKU_UNSPECIFIED",
		1:  "STOR_ACCT_SKU_STANDARD_LRS",
		2:  "STOR_ACCT_SKU_STANDARD_ZRS",
		3:  "STOR_ACCT_SKU_STANDARD_GRS",
		4:  "STOR_ACCT_SKU_STANDARD_GZRS",
		5:  "STOR_ACCT_SKU_STANDARD_RAGRS",
		6:  "STOR_ACCT_SKU_STANDARD_RAGZRS",
		7:  "STOR_ACCT_SKU_PREMIUM_LRS",
		8:  "STOR_ACCT_SKU_PREMIUM_ZRS",
		9:  "STOR_ACCT_SKU_STANDARDV2_LRS",
		10: "STOR_ACCT_SKU_STANDARDV2_ZRS",
		11: "STOR_ACCT_SKU_STANDARDV2_GRS",
		12: "STOR_ACCT_SKU_STANDARDV2_GZRS",
		13: "STOR_ACCT_SKU_PREMIUMV2_LRS",
		14: "STOR_ACCT_SKU_PREMIUMV2_ZRS",
	}
	StorAcctSKU_value = map[string]int32{
		"STOR_ACCT_SKU_UNSPECIFIED":     0,
		"STOR_ACCT_SKU_STANDARD_LRS":    1,
		"STOR_ACCT_SKU_STANDARD_ZRS":    2,
		"STOR_ACCT_SKU_STANDARD_GRS":    3,
		"STOR_ACCT_SKU_STANDARD_GZRS":   4,
		"STOR_ACCT_SKU_STANDARD_RAGRS":  5,
		"STOR_ACCT_SKU_STANDARD_RAGZRS": 6,
		"STOR_ACCT_SKU_PREMIUM_LRS":     7,
		"STOR_ACCT_SKU_PREMIUM_ZRS":     8,
		"STOR_ACCT_SKU_STANDARDV2_LRS":  9,
		"STOR_ACCT_SKU_STANDARDV2_ZRS":  10,
		"STOR_ACCT_SKU_STANDARDV2_GRS":  11,
		"STOR_ACCT_SKU_STANDARDV2_GZRS": 12,
		"STOR_ACCT_SKU_PREMIUMV2_LRS":   13,
		"STOR_ACCT_SKU_PREMIUMV2_ZRS":   14,
	}
)

func (x StorAcctSKU) Enum() *StorAcctSKU {
	p := new(StorAcctSKU)
	*p = x
	return p
}

func (x StorAcctSKU) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorAcctSKU) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_storage_proto_enumTypes[0].Descriptor()
}

func (StorAcctSKU) Type() protoreflect.EnumType {
	return &file_proto_templates_storage_proto_enumTypes[0]
}

func (x StorAcctSKU) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorAcctSKU.Descriptor instead.
func (StorAcctSKU) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{0}
}

type StorAcctKind int32

const (
	StorAcctKind_STOR_ACCT_KIND_UNSPECIFIED        StorAcctKind = 0
	StorAcctKind_STOR_ACCT_KIND_STORAGE_V2         StorAcctKind = 1 // Standard storage account type for blobs, file shares, queues, and tables. Recommended for most scenarios that use Azure Storage. If you want support for network file system (NFS) in Azure Files, use the premium file shares account type.
	StorAcctKind_STOR_ACCT_KIND_BLOCK_BLOB_STORAGE StorAcctKind = 2 // Premium storage account type for block blobs and append blobs. Recommended for scenarios with high transaction rates or that use smaller objects or require consistently low storage latency
	StorAcctKind_STOR_ACCT_KIND_FILE_STORAGE       StorAcctKind = 3 // Premium storage account type for file shares only. Recommended for enterprise or high-performance scale applications. Use this account type if you want a storage account that supports both Server Message Block (SMB) and NFS file shares.
)

// Enum value maps for StorAcctKind.
var (
	StorAcctKind_name = map[int32]string{
		0: "STOR_ACCT_KIND_UNSPECIFIED",
		1: "STOR_ACCT_KIND_STORAGE_V2",
		2: "STOR_ACCT_KIND_BLOCK_BLOB_STORAGE",
		3: "STOR_ACCT_KIND_FILE_STORAGE",
	}
	StorAcctKind_value = map[string]int32{
		"STOR_ACCT_KIND_UNSPECIFIED":        0,
		"STOR_ACCT_KIND_STORAGE_V2":         1,
		"STOR_ACCT_KIND_BLOCK_BLOB_STORAGE": 2,
		"STOR_ACCT_KIND_FILE_STORAGE":       3,
	}
)

func (x StorAcctKind) Enum() *StorAcctKind {
	p := new(StorAcctKind)
	*p = x
	return p
}

func (x StorAcctKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorAcctKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_storage_proto_enumTypes[1].Descriptor()
}

func (StorAcctKind) Type() protoreflect.EnumType {
	return &file_proto_templates_storage_proto_enumTypes[1]
}

func (x StorAcctKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorAcctKind.Descriptor instead.
func (StorAcctKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{1}
}

// stack for storage accounts, sql server, postgres flexible, and other resource types that are storage related ...
type Storage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StackName        string                 `protobuf:"bytes,1,opt,name=stack_name,json=stackName,proto3" json:"stack_name,omitempty"`
	ProviderVersions []*ProviderVersion     `protobuf:"bytes,2,rep,name=provider_versions,json=providerVersions,proto3" json:"provider_versions,omitempty"`
	DependsOn        []TemplateOptions      `protobuf:"varint,3,rep,packed,name=depends_on,json=dependsOn,proto3,enum=proto.templates.TemplateOptions" json:"depends_on,omitempty"`
	Request          *StorageRequest        `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	Response         *StorageResponse       `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_proto_templates_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Storage) GetStackName() string {
	if x != nil {
		return x.StackName
	}
	return ""
}

func (x *Storage) GetProviderVersions() []*ProviderVersion {
	if x != nil {
		return x.ProviderVersions
	}
	return nil
}

func (x *Storage) GetDependsOn() []TemplateOptions {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Storage) GetRequest() *StorageRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Storage) GetResponse() *StorageResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type StorageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefaultParams  *DefaultParams         `protobuf:"bytes,1,opt,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty"`
	StorageAccount *StorageAccountArgs    `protobuf:"bytes,2,opt,name=storage_account,json=storageAccount,proto3" json:"storage_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	mi := &file_proto_templates_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StorageRequest) GetDefaultParams() *DefaultParams {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *StorageRequest) GetStorageAccount() *StorageAccountArgs {
	if x != nil {
		return x.StorageAccount
	}
	return nil
}

type StorageResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	ResourceGroupName  string                     `protobuf:"bytes,1,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ResourceGroupId    string                     `protobuf:"bytes,2,opt,name=resource_group_id,json=resourceGroupId,proto3" json:"resource_group_id,omitempty"`
	StorageAccountName string                     `protobuf:"bytes,3,opt,name=storage_account_name,json=storageAccountName,proto3" json:"storage_account_name,omitempty"`
	StorageAccountId   string                     `protobuf:"bytes,4,opt,name=storage_account_id,json=storageAccountId,proto3" json:"storage_account_id,omitempty"`
	PrivateEndpoints   []*PrivateEndpointResponse `protobuf:"bytes,5,rep,name=private_endpoints,json=privateEndpoints,proto3" json:"private_endpoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_proto_templates_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageResponse) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

func (x *StorageResponse) GetResourceGroupId() string {
	if x != nil {
		return x.ResourceGroupId
	}
	return ""
}

func (x *StorageResponse) GetStorageAccountName() string {
	if x != nil {
		return x.StorageAccountName
	}
	return ""
}

func (x *StorageResponse) GetStorageAccountId() string {
	if x != nil {
		return x.StorageAccountId
	}
	return ""
}

func (x *StorageResponse) GetPrivateEndpoints() []*PrivateEndpointResponse {
	if x != nil {
		return x.PrivateEndpoints
	}
	return nil
}

type StorageAccountArgs struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Disabled              *bool                  `protobuf:"varint,1,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`                                                      // enabled by default
	HnsEnabled            bool                   `protobuf:"varint,2,opt,name=hns_enabled,json=hnsEnabled,proto3" json:"hns_enabled,omitempty"`                                      // disabled by default
	BlobAnonAccessEnabled bool                   `protobuf:"varint,3,opt,name=blob_anon_access_enabled,json=blobAnonAccessEnabled,proto3" json:"blob_anon_access_enabled,omitempty"` // disabled by default
	Kind                  StorAcctKind           `protobuf:"varint,4,opt,name=kind,proto3,enum=proto.templates.StorAcctKind" json:"kind,omitempty"`                                  // default is STOR_ACCT_KIND_STORAGE_V2 if unspecified
	Sku                   StorAcctSKU            `protobuf:"varint,5,opt,name=sku,proto3,enum=proto.templates.StorAcctSKU" json:"sku,omitempty"`                                     // default is STOR_ACCT_SKU_STANDARD_LRS if unspecified
	NetworkSettings       *ResourceNetworkArgs   `protobuf:"bytes,6,opt,name=network_settings,json=networkSettings,proto3" json:"network_settings,omitempty"`                        // default public network disabled with no private endpoints
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StorageAccountArgs) Reset() {
	*x = StorageAccountArgs{}
	mi := &file_proto_templates_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageAccountArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageAccountArgs) ProtoMessage() {}

func (x *StorageAccountArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageAccountArgs.ProtoReflect.Descriptor instead.
func (*StorageAccountArgs) Descriptor() ([]byte, []int) {
	return file_proto_templates_storage_proto_rawDescGZIP(), []int{3}
}

func (x *StorageAccountArgs) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *StorageAccountArgs) GetHnsEnabled() bool {
	if x != nil {
		return x.HnsEnabled
	}
	return false
}

func (x *StorageAccountArgs) GetBlobAnonAccessEnabled() bool {
	if x != nil {
		return x.BlobAnonAccessEnabled
	}
	return false
}

func (x *StorageAccountArgs) GetKind() StorAcctKind {
	if x != nil {
		return x.Kind
	}
	return StorAcctKind_STOR_ACCT_KIND_UNSPECIFIED
}

func (x *StorageAccountArgs) GetSku() StorAcctSKU {
	if x != nil {
		return x.Sku
	}
	return StorAcctSKU_STOR_ACCT_SKU_UNSPECIFIED
}

func (x *StorageAccountArgs) GetNetworkSettings() *ResourceNetworkArgs {
	if x != nil {
		return x.NetworkSettings
	}
	return nil
}

var File_proto_templates_storage_proto protoreflect.FileDescriptor

const file_proto_templates_storage_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/templates/storage.proto\x12\x0fproto.templates\x1a\x1cproto/templates/shared.proto\"\xb1\x02\n" +
	"\aStorage\x12\x1d\n" +
	"\n" +
	"stack_name\x18\x01 \x01(\tR\tstackName\x12M\n" +
	"\x11provider_versions\x18\x02 \x03(\v2 .proto.templates.ProviderVersionR\x10providerVersions\x12?\n" +
	"\n" +
	"depends_on\x18\x03 \x03(\x0e2 .proto.templates.TemplateOptionsR\tdependsOn\x129\n" +
	"\arequest\x18\x04 \x01(\v2\x1f.proto.templates.StorageRequestR\arequest\x12<\n" +
	"\bresponse\x18\x05 \x01(\v2 .proto.templates.StorageResponseR\bresponse\"\xa5\x01\n" +
	"\x0eStorageRequest\x12E\n" +
	"\x0edefault_params\x18\x01 \x01(\v2\x1e.proto.templates.DefaultParamsR\rdefaultParams\x12L\n" +
	"\x0fstorage_account\x18\x02 \x01(\v2#.proto.templates.StorageAccountArgsR\x0estorageAccount\"\xa4\x02\n" +
	"\x0fStorageResponse\x12.\n" +
	"\x13resource_group_name\x18\x01 \x01(\tR\x11resourceGroupName\x12*\n" +
	"\x11resource_group_id\x18\x02 \x01(\tR\x0fresourceGroupId\x120\n" +
	"\x14storage_account_name\x18\x03 \x01(\tR\x12storageAccountName\x12,\n" +
	"\x12storage_account_id\x18\x04 \x01(\tR\x10storageAccountId\x12U\n" +
	"\x11private_endpoints\x18\x05 \x03(\v2(.proto.templates.PrivateEndpointResponseR\x10privateEndpoints\"\xd0\x02\n" +
	"\x12StorageAccountArgs\x12\x1f\n" +
	"\bdisabled\x18\x01 \x01(\bH\x00R\bdisabled\x88\x01\x01\x12\x1f\n" +
	"\vhns_enabled\x18\x02 \x01(\bR\n" +
	"hnsEnabled\x127\n" +
	"\x18blob_anon_access_enabled\x18\x03 \x01(\bR\x15blobAnonAccessEnabled\x121\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1d.proto.templates.StorAcctKindR\x04kind\x12.\n" +
	"\x03sku\x18\x05 \x01(\x0e2\x1c.proto.templates.StorAcctSKUR\x03sku\x12O\n" +
	"\x10network_settings\x18\x06 \x01(\v2$.proto.templates.ResourceNetworkArgsR\x0fnetworkSettingsB\v\n" +
	"\t_disabled*\xfb\x03\n" +
	"\vStorAcctSKU\x12\x1d\n" +
	"\x19STOR_ACCT_SKU_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSTOR_ACCT_SKU_STANDARD_LRS\x10\x01\x12\x1e\n" +
	"\x1aSTOR_ACCT_SKU_STANDARD_ZRS\x10\x02\x12\x1e\n" +
	"\x1aSTOR_ACCT_SKU_STANDARD_GRS\x10\x03\x12\x1f\n" +
	"\x1bSTOR_ACCT_SKU_STANDARD_GZRS\x10\x04\x12 \n" +
	"\x1cSTOR_ACCT_SKU_STANDARD_RAGRS\x10\x05\x12!\n" +
	"\x1dSTOR_ACCT_SKU_STANDARD_RAGZRS\x10\x06\x12\x1d\n" +
	"\x19STOR_ACCT_SKU_PREMIUM_LRS\x10\a\x12\x1d\n" +
	"\x19STOR_ACCT_SKU_PREMIUM_ZRS\x10\b\x12 \n" +
	"\x1cSTOR_ACCT_SKU_STANDARDV2_LRS\x10\t\x12 \n" +
	"\x1cSTOR_ACCT_SKU_STANDARDV2_ZRS\x10\n" +
	"\x12 \n" +
	"\x1cSTOR_ACCT_SKU_STANDARDV2_GRS\x10\v\x12!\n" +
	"\x1dSTOR_ACCT_SKU_STANDARDV2_GZRS\x10\f\x12\x1f\n" +
	"\x1bSTOR_ACCT_SKU_PREMIUMV2_LRS\x10\r\x12\x1f\n" +
	"\x1bSTOR_ACCT_SKU_PREMIUMV2_ZRS\x10\x0e*\x95\x01\n" +
	"\fStorAcctKind\x12\x1e\n" +
	"\x1aSTOR_ACCT_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19STOR_ACCT_KIND_STORAGE_V2\x10\x01\x12%\n" +
	"!STOR_ACCT_KIND_BLOCK_BLOB_STORAGE\x10\x02\x12\x1f\n" +
	"\x1bSTOR_ACCT_KIND_FILE_STORAGE\x10\x03B>Z<github.com/htemuri/azure-pulumi-service-broker/pkg/templatesb\x06proto3"

var (
	file_proto_templates_storage_proto_rawDescOnce sync.Once
	file_proto_templates_storage_proto_rawDescData []byte
)

func file_proto_templates_storage_proto_rawDescGZIP() []byte {
	file_proto_templates_storage_proto_rawDescOnce.Do(func() {
		file_proto_templates_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_templates_storage_proto_rawDesc), len(file_proto_templates_storage_proto_rawDesc)))
	})
	return file_proto_templates_storage_proto_rawDescData
}

var file_proto_templates_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_templates_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_templates_storage_proto_goTypes = []any{
	(StorAcctSKU)(0),                // 0: proto.templates.StorAcctSKU
	(StorAcctKind)(0),               // 1: proto.templates.StorAcctKind
	(*Storage)(nil),                 // 2: proto.templates.Storage
	(*StorageRequest)(nil),          // 3: proto.templates.StorageRequest
	(*StorageResponse)(nil),         // 4: proto.templates.StorageResponse
	(*StorageAccountArgs)(nil),      // 5: proto.templates.StorageAccountArgs
	(*ProviderVersion)(nil),         // 6: proto.templates.ProviderVersion
	(TemplateOptions)(0),            // 7: proto.templates.TemplateOptions
	(*DefaultParams)(nil),           // 8: proto.templates.DefaultParams
	(*PrivateEndpointResponse)(nil), // 9: proto.templates.PrivateEndpointResponse
	(*ResourceNetworkArgs)(nil),     // 10: proto.templates.ResourceNetworkArgs
}
var file_proto_templates_storage_proto_depIdxs = []int32{
	6,  // 0: proto.templates.Storage.provider_versions:type_name -> proto.templates.ProviderVersion
	7,  // 1: proto.templates.Storage.depends_on:type_name -> proto.templates.TemplateOptions
	3,  // 2: proto.templates.Storage.request:type_name -> proto.templates.StorageRequest
	4,  // 3: proto.templates.Storage.response:type_name -> proto.templates.StorageResponse
	8,  // 4: proto.templates.StorageRequest.default_params:type_name -> proto.templates.DefaultParams
	5,  // 5: proto.templates.StorageRequest.storage_account:type_name -> proto.templates.StorageAccountArgs
	9,  // 6: proto.templates.StorageResponse.private_endpoints:type_name -> proto.templates.PrivateEndpointResponse
	1,  // 7: proto.templates.StorageAccountArgs.kind:type_name -> proto.templates.StorAcctKind
	0,  // 8: proto.templates.StorageAccountArgs.sku:type_name -> proto.templates.StorAcctSKU
	10, // 9: proto.templates.StorageAccountArgs.network_settings:type_name -> proto.templates.ResourceNetworkArgs
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_templates_storage_proto_init() }
func file_proto_templates_storage_proto_init() {
	if File_proto_templates_storage_proto != nil {
		return
	}
	file_proto_templates_shared_proto_init()
	file_proto_templates_storage_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_templates_storage_proto_rawDesc), len(file_proto_templates_storage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_storage_proto_goTypes,
		DependencyIndexes: file_proto_templates_storage_proto_depIdxs,
		EnumInfos:         file_proto_templates_storage_proto_enumTypes,
		MessageInfos:      file_proto_templates_storage_proto_msgTypes,
	}.Build()
	File_proto_templates_storage_proto = out.File
	file_proto_templates_storage_proto_goTypes = nil
	file_proto_templates_storage_proto_depIdxs = nil
}
