// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/templates/template.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_SUCCESS     Status = 1
	Status_STATUS_ERROR       Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SUCCESS":     1,
		"STATUS_ERROR":       2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_template_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_templates_template_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{0}
}

type TemplateOptions int32

const (
	TemplateOptions_TEMPLATE_OPTIONS_UNSPECIFIED TemplateOptions = 0
	TemplateOptions_TEMPLATE_OPTIONS_BASE        TemplateOptions = 1
	TemplateOptions_TEMPLATE_OPTIONS_SECURITY    TemplateOptions = 2
	TemplateOptions_TEMPLATE_OPTIONS_STORAGE     TemplateOptions = 3
)

// Enum value maps for TemplateOptions.
var (
	TemplateOptions_name = map[int32]string{
		0: "TEMPLATE_OPTIONS_UNSPECIFIED",
		1: "TEMPLATE_OPTIONS_BASE",
		2: "TEMPLATE_OPTIONS_SECURITY",
		3: "TEMPLATE_OPTIONS_STORAGE",
	}
	TemplateOptions_value = map[string]int32{
		"TEMPLATE_OPTIONS_UNSPECIFIED": 0,
		"TEMPLATE_OPTIONS_BASE":        1,
		"TEMPLATE_OPTIONS_SECURITY":    2,
		"TEMPLATE_OPTIONS_STORAGE":     3,
	}
)

func (x TemplateOptions) Enum() *TemplateOptions {
	p := new(TemplateOptions)
	*p = x
	return p
}

func (x TemplateOptions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemplateOptions) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_templates_template_proto_enumTypes[1].Descriptor()
}

func (TemplateOptions) Type() protoreflect.EnumType {
	return &file_proto_templates_template_proto_enumTypes[1]
}

func (x TemplateOptions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemplateOptions.Descriptor instead.
func (TemplateOptions) EnumDescriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{1}
}

type Templates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Template:
	//
	//	*Templates_Base
	//	*Templates_Security
	//	*Templates_Storage
	Template isTemplates_Template `protobuf_oneof:"template"`
}

func (x *Templates) Reset() {
	*x = Templates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Templates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Templates) ProtoMessage() {}

func (x *Templates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Templates.ProtoReflect.Descriptor instead.
func (*Templates) Descriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{0}
}

func (m *Templates) GetTemplate() isTemplates_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (x *Templates) GetBase() *Base {
	if x, ok := x.GetTemplate().(*Templates_Base); ok {
		return x.Base
	}
	return nil
}

func (x *Templates) GetSecurity() *Security {
	if x, ok := x.GetTemplate().(*Templates_Security); ok {
		return x.Security
	}
	return nil
}

func (x *Templates) GetStorage() *Storage {
	if x, ok := x.GetTemplate().(*Templates_Storage); ok {
		return x.Storage
	}
	return nil
}

type isTemplates_Template interface {
	isTemplates_Template()
}

type Templates_Base struct {
	Base *Base `protobuf:"bytes,1,opt,name=base,proto3,oneof"`
}

type Templates_Security struct {
	Security *Security `protobuf:"bytes,2,opt,name=security,proto3,oneof"`
}

type Templates_Storage struct {
	Storage *Storage `protobuf:"bytes,3,opt,name=storage,proto3,oneof"`
}

func (*Templates_Base) isTemplates_Template() {}

func (*Templates_Security) isTemplates_Template() {}

func (*Templates_Storage) isTemplates_Template() {}

type TemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.templates.Status" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are assignable to Response:
	//
	//	*TemplatesResponse_Base
	//	*TemplatesResponse_Security
	//	*TemplatesResponse_Storage
	Response isTemplatesResponse_Response `protobuf_oneof:"response"`
}

func (x *TemplatesResponse) Reset() {
	*x = TemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatesResponse) ProtoMessage() {}

func (x *TemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatesResponse.ProtoReflect.Descriptor instead.
func (*TemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{1}
}

func (x *TemplatesResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TemplatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (m *TemplatesResponse) GetResponse() isTemplatesResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TemplatesResponse) GetBase() *BaseResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Base); ok {
		return x.Base
	}
	return nil
}

func (x *TemplatesResponse) GetSecurity() *SecurityResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Security); ok {
		return x.Security
	}
	return nil
}

func (x *TemplatesResponse) GetStorage() *StorageResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Storage); ok {
		return x.Storage
	}
	return nil
}

type isTemplatesResponse_Response interface {
	isTemplatesResponse_Response()
}

type TemplatesResponse_Base struct {
	Base *BaseResponse `protobuf:"bytes,3,opt,name=base,proto3,oneof"`
}

type TemplatesResponse_Security struct {
	Security *SecurityResponse `protobuf:"bytes,4,opt,name=security,proto3,oneof"`
}

type TemplatesResponse_Storage struct {
	Storage *StorageResponse `protobuf:"bytes,5,opt,name=storage,proto3,oneof"`
}

func (*TemplatesResponse_Base) isTemplatesResponse_Response() {}

func (*TemplatesResponse_Security) isTemplatesResponse_Response() {}

func (*TemplatesResponse_Storage) isTemplatesResponse_Response() {}

var File_proto_templates_template_proto protoreflect.FileDescriptor

var file_proto_templates_template_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a,
	0x09, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x34, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x22, 0x9a, 0x02, 0x0a, 0x11, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x33, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a,
	0x46, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x2a, 0x8b, 0x01, 0x0a, 0x0f, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x54,
	0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a,
	0x15, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e,
	0x53, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x54, 0x45, 0x4d, 0x50,
	0x4c, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x53, 0x45, 0x43,
	0x55, 0x52, 0x49, 0x54, 0x59, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x54, 0x45, 0x4d, 0x50, 0x4c,
	0x41, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x52,
	0x41, 0x47, 0x45, 0x10, 0x03, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74, 0x65, 0x6d, 0x75, 0x72, 0x69, 0x2f, 0x61, 0x7a, 0x75, 0x72,
	0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_templates_template_proto_rawDescOnce sync.Once
	file_proto_templates_template_proto_rawDescData = file_proto_templates_template_proto_rawDesc
)

func file_proto_templates_template_proto_rawDescGZIP() []byte {
	file_proto_templates_template_proto_rawDescOnce.Do(func() {
		file_proto_templates_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_templates_template_proto_rawDescData)
	})
	return file_proto_templates_template_proto_rawDescData
}

var file_proto_templates_template_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_templates_template_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_templates_template_proto_goTypes = []interface{}{
	(Status)(0),               // 0: proto.templates.Status
	(TemplateOptions)(0),      // 1: proto.templates.TemplateOptions
	(*Templates)(nil),         // 2: proto.templates.Templates
	(*TemplatesResponse)(nil), // 3: proto.templates.TemplatesResponse
	(*Base)(nil),              // 4: proto.templates.Base
	(*Security)(nil),          // 5: proto.templates.Security
	(*Storage)(nil),           // 6: proto.templates.Storage
	(*BaseResponse)(nil),      // 7: proto.templates.BaseResponse
	(*SecurityResponse)(nil),  // 8: proto.templates.SecurityResponse
	(*StorageResponse)(nil),   // 9: proto.templates.StorageResponse
}
var file_proto_templates_template_proto_depIdxs = []int32{
	4, // 0: proto.templates.Templates.base:type_name -> proto.templates.Base
	5, // 1: proto.templates.Templates.security:type_name -> proto.templates.Security
	6, // 2: proto.templates.Templates.storage:type_name -> proto.templates.Storage
	0, // 3: proto.templates.TemplatesResponse.status:type_name -> proto.templates.Status
	7, // 4: proto.templates.TemplatesResponse.base:type_name -> proto.templates.BaseResponse
	8, // 5: proto.templates.TemplatesResponse.security:type_name -> proto.templates.SecurityResponse
	9, // 6: proto.templates.TemplatesResponse.storage:type_name -> proto.templates.StorageResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_templates_template_proto_init() }
func file_proto_templates_template_proto_init() {
	if File_proto_templates_template_proto != nil {
		return
	}
	file_proto_templates_base_proto_init()
	file_proto_templates_security_proto_init()
	file_proto_templates_storage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_templates_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Templates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_templates_template_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Templates_Base)(nil),
		(*Templates_Security)(nil),
		(*Templates_Storage)(nil),
	}
	file_proto_templates_template_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TemplatesResponse_Base)(nil),
		(*TemplatesResponse_Security)(nil),
		(*TemplatesResponse_Storage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_templates_template_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_template_proto_goTypes,
		DependencyIndexes: file_proto_templates_template_proto_depIdxs,
		EnumInfos:         file_proto_templates_template_proto_enumTypes,
		MessageInfos:      file_proto_templates_template_proto_msgTypes,
	}.Build()
	File_proto_templates_template_proto = out.File
	file_proto_templates_template_proto_rawDesc = nil
	file_proto_templates_template_proto_goTypes = nil
	file_proto_templates_template_proto_depIdxs = nil
}
