// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/templates/template.proto

package templates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Templates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Template:
	//
	//	*Templates_Base
	//	*Templates_Security
	//	*Templates_Storage
	Template isTemplates_Template `protobuf_oneof:"template"`
}

func (x *Templates) Reset() {
	*x = Templates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Templates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Templates) ProtoMessage() {}

func (x *Templates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Templates.ProtoReflect.Descriptor instead.
func (*Templates) Descriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{0}
}

func (m *Templates) GetTemplate() isTemplates_Template {
	if m != nil {
		return m.Template
	}
	return nil
}

func (x *Templates) GetBase() *Base {
	if x, ok := x.GetTemplate().(*Templates_Base); ok {
		return x.Base
	}
	return nil
}

func (x *Templates) GetSecurity() *Security {
	if x, ok := x.GetTemplate().(*Templates_Security); ok {
		return x.Security
	}
	return nil
}

func (x *Templates) GetStorage() *Storage {
	if x, ok := x.GetTemplate().(*Templates_Storage); ok {
		return x.Storage
	}
	return nil
}

type isTemplates_Template interface {
	isTemplates_Template()
}

type Templates_Base struct {
	Base *Base `protobuf:"bytes,1,opt,name=base,proto3,oneof"`
}

type Templates_Security struct {
	Security *Security `protobuf:"bytes,2,opt,name=security,proto3,oneof"`
}

type Templates_Storage struct {
	Storage *Storage `protobuf:"bytes,3,opt,name=storage,proto3,oneof"`
}

func (*Templates_Base) isTemplates_Template() {}

func (*Templates_Security) isTemplates_Template() {}

func (*Templates_Storage) isTemplates_Template() {}

type TemplatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*TemplatesRequest_Base
	//	*TemplatesRequest_Security
	//	*TemplatesRequest_Storage
	Request isTemplatesRequest_Request `protobuf_oneof:"request"`
}

func (x *TemplatesRequest) Reset() {
	*x = TemplatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatesRequest) ProtoMessage() {}

func (x *TemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatesRequest.ProtoReflect.Descriptor instead.
func (*TemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{1}
}

func (m *TemplatesRequest) GetRequest() isTemplatesRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *TemplatesRequest) GetBase() *BaseRequest {
	if x, ok := x.GetRequest().(*TemplatesRequest_Base); ok {
		return x.Base
	}
	return nil
}

func (x *TemplatesRequest) GetSecurity() *SecurityRequest {
	if x, ok := x.GetRequest().(*TemplatesRequest_Security); ok {
		return x.Security
	}
	return nil
}

func (x *TemplatesRequest) GetStorage() *StorageRequest {
	if x, ok := x.GetRequest().(*TemplatesRequest_Storage); ok {
		return x.Storage
	}
	return nil
}

type isTemplatesRequest_Request interface {
	isTemplatesRequest_Request()
}

type TemplatesRequest_Base struct {
	Base *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3,oneof"`
}

type TemplatesRequest_Security struct {
	Security *SecurityRequest `protobuf:"bytes,2,opt,name=security,proto3,oneof"`
}

type TemplatesRequest_Storage struct {
	Storage *StorageRequest `protobuf:"bytes,3,opt,name=storage,proto3,oneof"`
}

func (*TemplatesRequest_Base) isTemplatesRequest_Request() {}

func (*TemplatesRequest_Security) isTemplatesRequest_Request() {}

func (*TemplatesRequest_Storage) isTemplatesRequest_Request() {}

type TemplatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.templates.Status" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are assignable to Response:
	//
	//	*TemplatesResponse_Base
	//	*TemplatesResponse_Security
	//	*TemplatesResponse_Storage
	Response isTemplatesResponse_Response `protobuf_oneof:"response"`
}

func (x *TemplatesResponse) Reset() {
	*x = TemplatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_templates_template_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatesResponse) ProtoMessage() {}

func (x *TemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_templates_template_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatesResponse.ProtoReflect.Descriptor instead.
func (*TemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_templates_template_proto_rawDescGZIP(), []int{2}
}

func (x *TemplatesResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TemplatesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (m *TemplatesResponse) GetResponse() isTemplatesResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TemplatesResponse) GetBase() *BaseResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Base); ok {
		return x.Base
	}
	return nil
}

func (x *TemplatesResponse) GetSecurity() *SecurityResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Security); ok {
		return x.Security
	}
	return nil
}

func (x *TemplatesResponse) GetStorage() *StorageResponse {
	if x, ok := x.GetResponse().(*TemplatesResponse_Storage); ok {
		return x.Storage
	}
	return nil
}

type isTemplatesResponse_Response interface {
	isTemplatesResponse_Response()
}

type TemplatesResponse_Base struct {
	Base *BaseResponse `protobuf:"bytes,3,opt,name=base,proto3,oneof"`
}

type TemplatesResponse_Security struct {
	Security *SecurityResponse `protobuf:"bytes,4,opt,name=security,proto3,oneof"`
}

type TemplatesResponse_Storage struct {
	Storage *StorageResponse `protobuf:"bytes,5,opt,name=storage,proto3,oneof"`
}

func (*TemplatesResponse_Base) isTemplatesResponse_Response() {}

func (*TemplatesResponse_Security) isTemplatesResponse_Response() {}

func (*TemplatesResponse_Storage) isTemplatesResponse_Response() {}

var File_proto_templates_template_proto protoreflect.FileDescriptor

var file_proto_templates_template_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x09, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x34,
	0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x22, 0xce, 0x01, 0x0a, 0x10, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x9a, 0x02, 0x0a, 0x11, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33,
	0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74, 0x65,
	0x6d, 0x75, 0x72, 0x69, 0x2f, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75, 0x6d,
	0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_templates_template_proto_rawDescOnce sync.Once
	file_proto_templates_template_proto_rawDescData = file_proto_templates_template_proto_rawDesc
)

func file_proto_templates_template_proto_rawDescGZIP() []byte {
	file_proto_templates_template_proto_rawDescOnce.Do(func() {
		file_proto_templates_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_templates_template_proto_rawDescData)
	})
	return file_proto_templates_template_proto_rawDescData
}

var file_proto_templates_template_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_templates_template_proto_goTypes = []interface{}{
	(*Templates)(nil),         // 0: proto.templates.Templates
	(*TemplatesRequest)(nil),  // 1: proto.templates.TemplatesRequest
	(*TemplatesResponse)(nil), // 2: proto.templates.TemplatesResponse
	(*Base)(nil),              // 3: proto.templates.Base
	(*Security)(nil),          // 4: proto.templates.Security
	(*Storage)(nil),           // 5: proto.templates.Storage
	(*BaseRequest)(nil),       // 6: proto.templates.BaseRequest
	(*SecurityRequest)(nil),   // 7: proto.templates.SecurityRequest
	(*StorageRequest)(nil),    // 8: proto.templates.StorageRequest
	(Status)(0),               // 9: proto.templates.Status
	(*BaseResponse)(nil),      // 10: proto.templates.BaseResponse
	(*SecurityResponse)(nil),  // 11: proto.templates.SecurityResponse
	(*StorageResponse)(nil),   // 12: proto.templates.StorageResponse
}
var file_proto_templates_template_proto_depIdxs = []int32{
	3,  // 0: proto.templates.Templates.base:type_name -> proto.templates.Base
	4,  // 1: proto.templates.Templates.security:type_name -> proto.templates.Security
	5,  // 2: proto.templates.Templates.storage:type_name -> proto.templates.Storage
	6,  // 3: proto.templates.TemplatesRequest.base:type_name -> proto.templates.BaseRequest
	7,  // 4: proto.templates.TemplatesRequest.security:type_name -> proto.templates.SecurityRequest
	8,  // 5: proto.templates.TemplatesRequest.storage:type_name -> proto.templates.StorageRequest
	9,  // 6: proto.templates.TemplatesResponse.status:type_name -> proto.templates.Status
	10, // 7: proto.templates.TemplatesResponse.base:type_name -> proto.templates.BaseResponse
	11, // 8: proto.templates.TemplatesResponse.security:type_name -> proto.templates.SecurityResponse
	12, // 9: proto.templates.TemplatesResponse.storage:type_name -> proto.templates.StorageResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_templates_template_proto_init() }
func file_proto_templates_template_proto_init() {
	if File_proto_templates_template_proto != nil {
		return
	}
	file_proto_templates_base_proto_init()
	file_proto_templates_security_proto_init()
	file_proto_templates_shared_proto_init()
	file_proto_templates_storage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_templates_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Templates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_templates_template_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_templates_template_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Templates_Base)(nil),
		(*Templates_Security)(nil),
		(*Templates_Storage)(nil),
	}
	file_proto_templates_template_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TemplatesRequest_Base)(nil),
		(*TemplatesRequest_Security)(nil),
		(*TemplatesRequest_Storage)(nil),
	}
	file_proto_templates_template_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*TemplatesResponse_Base)(nil),
		(*TemplatesResponse_Security)(nil),
		(*TemplatesResponse_Storage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_templates_template_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_templates_template_proto_goTypes,
		DependencyIndexes: file_proto_templates_template_proto_depIdxs,
		MessageInfos:      file_proto_templates_template_proto_msgTypes,
	}.Build()
	File_proto_templates_template_proto = out.File
	file_proto_templates_template_proto_rawDesc = nil
	file_proto_templates_template_proto_goTypes = nil
	file_proto_templates_template_proto_depIdxs = nil
}
