// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/project/project.proto

package project

import (
	templates "github.com/htemuri/azure-pulumi-service-broker/pkg/templates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSPECIFIED RoleType = 0
	RoleType_ROLE_TYPE_ADMIN       RoleType = 1
	RoleType_ROLE_TYPE_DEVELOPER   RoleType = 2
	RoleType_ROLE_TYPE_READER      RoleType = 3
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNSPECIFIED",
		1: "ROLE_TYPE_ADMIN",
		2: "ROLE_TYPE_DEVELOPER",
		3: "ROLE_TYPE_READER",
	}
	RoleType_value = map[string]int32{
		"ROLE_TYPE_UNSPECIFIED": 0,
		"ROLE_TYPE_ADMIN":       1,
		"ROLE_TYPE_DEVELOPER":   2,
		"ROLE_TYPE_READER":      3,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_project_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_proto_project_project_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{0}
}

type StorageAccountSubResource int32

const (
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED StorageAccountSubResource = 0
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_BLOB        StorageAccountSubResource = 1
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_DFS         StorageAccountSubResource = 2
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE       StorageAccountSubResource = 3
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_FILE        StorageAccountSubResource = 4
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_WEB         StorageAccountSubResource = 5
)

// Enum value maps for StorageAccountSubResource.
var (
	StorageAccountSubResource_name = map[int32]string{
		0: "STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED",
		1: "STORAGE_ACCOUNT_SUB_RESOURCE_BLOB",
		2: "STORAGE_ACCOUNT_SUB_RESOURCE_DFS",
		3: "STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE",
		4: "STORAGE_ACCOUNT_SUB_RESOURCE_FILE",
		5: "STORAGE_ACCOUNT_SUB_RESOURCE_WEB",
	}
	StorageAccountSubResource_value = map[string]int32{
		"STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED": 0,
		"STORAGE_ACCOUNT_SUB_RESOURCE_BLOB":        1,
		"STORAGE_ACCOUNT_SUB_RESOURCE_DFS":         2,
		"STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE":       3,
		"STORAGE_ACCOUNT_SUB_RESOURCE_FILE":        4,
		"STORAGE_ACCOUNT_SUB_RESOURCE_WEB":         5,
	}
)

func (x StorageAccountSubResource) Enum() *StorageAccountSubResource {
	p := new(StorageAccountSubResource)
	*p = x
	return p
}

func (x StorageAccountSubResource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageAccountSubResource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_project_proto_enumTypes[1].Descriptor()
}

func (StorageAccountSubResource) Type() protoreflect.EnumType {
	return &file_proto_project_project_proto_enumTypes[1]
}

func (x StorageAccountSubResource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageAccountSubResource.Descriptor instead.
func (StorageAccountSubResource) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{1}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Environment   templates.Environment  `protobuf:"varint,2,opt,name=environment,proto3,enum=proto.templates.Environment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetEnvironment() templates.Environment {
	if x != nil {
		return x.Environment
	}
	return templates.Environment(0)
}

type ProjectResponse struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Name              string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TemplateResponses []*templates.TemplatesResponse `protobuf:"bytes,2,rep,name=template_responses,json=templateResponses,proto3" json:"template_responses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_proto_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectResponse) GetTemplateResponses() []*templates.TemplatesResponse {
	if x != nil {
		return x.TemplateResponses
	}
	return nil
}

type UserPersonaEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          RoleType               `protobuf:"varint,1,opt,name=role,proto3,enum=proto.project.RoleType" json:"role,omitempty"`
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPersonaEntry) Reset() {
	*x = UserPersonaEntry{}
	mi := &file_proto_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPersonaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPersonaEntry) ProtoMessage() {}

func (x *UserPersonaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPersonaEntry.ProtoReflect.Descriptor instead.
func (*UserPersonaEntry) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *UserPersonaEntry) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ROLE_TYPE_UNSPECIFIED
}

func (x *UserPersonaEntry) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GroupPersonaEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          RoleType               `protobuf:"varint,1,opt,name=role,proto3,enum=proto.project.RoleType" json:"role,omitempty"`
	Group         *Group                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPersonaEntry) Reset() {
	*x = GroupPersonaEntry{}
	mi := &file_proto_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPersonaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPersonaEntry) ProtoMessage() {}

func (x *GroupPersonaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPersonaEntry.ProtoReflect.Descriptor instead.
func (*GroupPersonaEntry) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *GroupPersonaEntry) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ROLE_TYPE_UNSPECIFIED
}

func (x *GroupPersonaEntry) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserPrincipalName string                 `protobuf:"bytes,1,opt,name=user_principal_name,json=userPrincipalName,proto3" json:"user_principal_name,omitempty"`
	ObjectId          string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserPrincipalName() string {
	if x != nil {
		return x.UserPrincipalName
	}
	return ""
}

func (x *User) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_project_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Group) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type StorageAccountOptions struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Enabled       bool                        `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SubResources  []StorageAccountSubResource `protobuf:"varint,2,rep,packed,name=sub_resources,json=subResources,proto3,enum=proto.project.StorageAccountSubResource" json:"sub_resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageAccountOptions) Reset() {
	*x = StorageAccountOptions{}
	mi := &file_proto_project_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageAccountOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageAccountOptions) ProtoMessage() {}

func (x *StorageAccountOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageAccountOptions.ProtoReflect.Descriptor instead.
func (*StorageAccountOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{6}
}

func (x *StorageAccountOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StorageAccountOptions) GetSubResources() []StorageAccountSubResource {
	if x != nil {
		return x.SubResources
	}
	return nil
}

type KeyVaultOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyVaultOptions) Reset() {
	*x = KeyVaultOptions{}
	mi := &file_proto_project_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVaultOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVaultOptions) ProtoMessage() {}

func (x *KeyVaultOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVaultOptions.ProtoReflect.Descriptor instead.
func (*KeyVaultOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{7}
}

func (x *KeyVaultOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ServicePrincipalOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePrincipalOptions) Reset() {
	*x = ServicePrincipalOptions{}
	mi := &file_proto_project_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePrincipalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePrincipalOptions) ProtoMessage() {}

func (x *ServicePrincipalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePrincipalOptions.ProtoReflect.Descriptor instead.
func (*ServicePrincipalOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{8}
}

func (x *ServicePrincipalOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DataFactoryOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFactoryOptions) Reset() {
	*x = DataFactoryOptions{}
	mi := &file_proto_project_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFactoryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFactoryOptions) ProtoMessage() {}

func (x *DataFactoryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFactoryOptions.ProtoReflect.Descriptor instead.
func (*DataFactoryOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{9}
}

func (x *DataFactoryOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_proto_project_project_proto protoreflect.FileDescriptor

const file_proto_project_project_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/project/project.proto\x12\rproto.project\x1a\x1cproto/templates/shared.proto\x1a\x1eproto/templates/template.proto\"]\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\venvironment\x18\x02 \x01(\x0e2\x1c.proto.templates.EnvironmentR\venvironment\"x\n" +
	"\x0fProjectResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12Q\n" +
	"\x12template_responses\x18\x02 \x03(\v2\".proto.templates.TemplatesResponseR\x11templateResponses\"j\n" +
	"\x10UserPersonaEntry\x12+\n" +
	"\x04role\x18\x01 \x01(\x0e2\x17.proto.project.RoleTypeR\x04role\x12)\n" +
	"\x05users\x18\x02 \x03(\v2\x13.proto.project.UserR\x05users\"l\n" +
	"\x11GroupPersonaEntry\x12+\n" +
	"\x04role\x18\x01 \x01(\x0e2\x17.proto.project.RoleTypeR\x04role\x12*\n" +
	"\x05group\x18\x02 \x01(\v2\x14.proto.project.GroupR\x05group\"S\n" +
	"\x04User\x12.\n" +
	"\x13user_principal_name\x18\x01 \x01(\tR\x11userPrincipalName\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"G\n" +
	"\x05Group\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"\x80\x01\n" +
	"\x15StorageAccountOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12M\n" +
	"\rsub_resources\x18\x02 \x03(\x0e2(.proto.project.StorageAccountSubResourceR\fsubResources\"+\n" +
	"\x0fKeyVaultOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"3\n" +
	"\x17ServicePrincipalOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\".\n" +
	"\x12DataFactoryOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled*i\n" +
	"\bRoleType\x12\x19\n" +
	"\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fROLE_TYPE_ADMIN\x10\x01\x12\x17\n" +
	"\x13ROLE_TYPE_DEVELOPER\x10\x02\x12\x14\n" +
	"\x10ROLE_TYPE_READER\x10\x03*\x8b\x02\n" +
	"\x19StorageAccountSubResource\x12,\n" +
	"(STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED\x10\x00\x12%\n" +
	"!STORAGE_ACCOUNT_SUB_RESOURCE_BLOB\x10\x01\x12$\n" +
	" STORAGE_ACCOUNT_SUB_RESOURCE_DFS\x10\x02\x12&\n" +
	"\"STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE\x10\x03\x12%\n" +
	"!STORAGE_ACCOUNT_SUB_RESOURCE_FILE\x10\x04\x12$\n" +
	" STORAGE_ACCOUNT_SUB_RESOURCE_WEB\x10\x05B<Z:github.com/htemuri/azure-pulumi-service-broker/pkg/projectb\x06proto3"

var (
	file_proto_project_project_proto_rawDescOnce sync.Once
	file_proto_project_project_proto_rawDescData []byte
)

func file_proto_project_project_proto_rawDescGZIP() []byte {
	file_proto_project_project_proto_rawDescOnce.Do(func() {
		file_proto_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_project_proto_rawDesc), len(file_proto_project_project_proto_rawDesc)))
	})
	return file_proto_project_project_proto_rawDescData
}

var file_proto_project_project_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_project_project_proto_goTypes = []any{
	(RoleType)(0),                       // 0: proto.project.RoleType
	(StorageAccountSubResource)(0),      // 1: proto.project.StorageAccountSubResource
	(*Project)(nil),                     // 2: proto.project.Project
	(*ProjectResponse)(nil),             // 3: proto.project.ProjectResponse
	(*UserPersonaEntry)(nil),            // 4: proto.project.UserPersonaEntry
	(*GroupPersonaEntry)(nil),           // 5: proto.project.GroupPersonaEntry
	(*User)(nil),                        // 6: proto.project.User
	(*Group)(nil),                       // 7: proto.project.Group
	(*StorageAccountOptions)(nil),       // 8: proto.project.StorageAccountOptions
	(*KeyVaultOptions)(nil),             // 9: proto.project.KeyVaultOptions
	(*ServicePrincipalOptions)(nil),     // 10: proto.project.ServicePrincipalOptions
	(*DataFactoryOptions)(nil),          // 11: proto.project.DataFactoryOptions
	(templates.Environment)(0),          // 12: proto.templates.Environment
	(*templates.TemplatesResponse)(nil), // 13: proto.templates.TemplatesResponse
}
var file_proto_project_project_proto_depIdxs = []int32{
	12, // 0: proto.project.Project.environment:type_name -> proto.templates.Environment
	13, // 1: proto.project.ProjectResponse.template_responses:type_name -> proto.templates.TemplatesResponse
	0,  // 2: proto.project.UserPersonaEntry.role:type_name -> proto.project.RoleType
	6,  // 3: proto.project.UserPersonaEntry.users:type_name -> proto.project.User
	0,  // 4: proto.project.GroupPersonaEntry.role:type_name -> proto.project.RoleType
	7,  // 5: proto.project.GroupPersonaEntry.group:type_name -> proto.project.Group
	1,  // 6: proto.project.StorageAccountOptions.sub_resources:type_name -> proto.project.StorageAccountSubResource
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_project_project_proto_init() }
func file_proto_project_project_proto_init() {
	if File_proto_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_project_proto_rawDesc), len(file_proto_project_project_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_project_project_proto_goTypes,
		DependencyIndexes: file_proto_project_project_proto_depIdxs,
		EnumInfos:         file_proto_project_project_proto_enumTypes,
		MessageInfos:      file_proto_project_project_proto_msgTypes,
	}.Build()
	File_proto_project_project_proto = out.File
	file_proto_project_project_proto_goTypes = nil
	file_proto_project_project_proto_depIdxs = nil
}
