// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/broker/broker.proto

package broker

import (
	project "github.com/htemuri/azure-pulumi-service-broker/pkg/project"
	templates "github.com/htemuri/azure-pulumi-service-broker/pkg/templates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProjectRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Project          *project.Project              `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	TemplateRequests []*templates.TemplatesRequest `protobuf:"bytes,2,rep,name=template_requests,json=templateRequests,proto3" json:"template_requests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_proto_broker_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_broker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetProject() *project.Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *CreateProjectRequest) GetTemplateRequests() []*templates.TemplatesRequest {
	if x != nil {
		return x.TemplateRequests
	}
	return nil
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Status        templates.Status       `protobuf:"varint,3,opt,name=status,proto3,enum=proto.templates.Status" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_proto_broker_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_broker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CreateProjectResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CreateProjectResponse) GetStatus() templates.Status {
	if x != nil {
		return x.Status
	}
	return templates.Status(0)
}

func (x *CreateProjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetProjectStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectStatusRequest) Reset() {
	*x = GetProjectStatusRequest{}
	mi := &file_proto_broker_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatusRequest) ProtoMessage() {}

func (x *GetProjectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProjectStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_broker_proto_rawDescGZIP(), []int{2}
}

func (x *GetProjectStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type GetProjectStatusResponse struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	ProjectName       string                         `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Status            templates.Status               `protobuf:"varint,2,opt,name=status,proto3,enum=proto.templates.Status" json:"status,omitempty"`
	TemplateResponses []*templates.TemplatesResponse `protobuf:"bytes,3,rep,name=template_responses,json=templateResponses,proto3" json:"template_responses,omitempty"`
	Error             string                         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProjectStatusResponse) Reset() {
	*x = GetProjectStatusResponse{}
	mi := &file_proto_broker_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectStatusResponse) ProtoMessage() {}

func (x *GetProjectStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProjectStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_broker_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectStatusResponse) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *GetProjectStatusResponse) GetStatus() templates.Status {
	if x != nil {
		return x.Status
	}
	return templates.Status(0)
}

func (x *GetProjectStatusResponse) GetTemplateResponses() []*templates.TemplatesResponse {
	if x != nil {
		return x.TemplateResponses
	}
	return nil
}

func (x *GetProjectStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_broker_broker_proto protoreflect.FileDescriptor

const file_proto_broker_broker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/broker/broker.proto\x12\fproto.broker\x1a\x1bproto/project/project.proto\x1a\x1cproto/templates/shared.proto\x1a\x1eproto/templates/template.proto\"\x98\x01\n" +
	"\x14CreateProjectRequest\x120\n" +
	"\aproject\x18\x01 \x01(\v2\x16.proto.project.ProjectR\aproject\x12N\n" +
	"\x11template_requests\x18\x02 \x03(\v2!.proto.templates.TemplatesRequestR\x10templateRequests\"\xa6\x01\n" +
	"\x15CreateProjectResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.proto.templates.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\">\n" +
	"\x17GetProjectStatusRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\"\xd7\x01\n" +
	"\x18GetProjectStatusResponse\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.proto.templates.StatusR\x06status\x12Q\n" +
	"\x12template_responses\x18\x03 \x03(\v2\".proto.templates.TemplatesResponseR\x11templateResponses\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xcc\x01\n" +
	"\rBrokerService\x12X\n" +
	"\rCreateProject\x12\".proto.broker.CreateProjectRequest\x1a#.proto.broker.CreateProjectResponse\x12a\n" +
	"\x10GetProjectStatus\x12%.proto.broker.GetProjectStatusRequest\x1a&.proto.broker.GetProjectStatusResponseB;Z9github.com/htemuri/azure-pulumi-service-broker/pkg/brokerb\x06proto3"

var (
	file_proto_broker_broker_proto_rawDescOnce sync.Once
	file_proto_broker_broker_proto_rawDescData []byte
)

func file_proto_broker_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_broker_proto_rawDesc), len(file_proto_broker_broker_proto_rawDesc)))
	})
	return file_proto_broker_broker_proto_rawDescData
}

var file_proto_broker_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_broker_broker_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),        // 0: proto.broker.CreateProjectRequest
	(*CreateProjectResponse)(nil),       // 1: proto.broker.CreateProjectResponse
	(*GetProjectStatusRequest)(nil),     // 2: proto.broker.GetProjectStatusRequest
	(*GetProjectStatusResponse)(nil),    // 3: proto.broker.GetProjectStatusResponse
	(*project.Project)(nil),             // 4: proto.project.Project
	(*templates.TemplatesRequest)(nil),  // 5: proto.templates.TemplatesRequest
	(templates.Status)(0),               // 6: proto.templates.Status
	(*templates.TemplatesResponse)(nil), // 7: proto.templates.TemplatesResponse
}
var file_proto_broker_broker_proto_depIdxs = []int32{
	4, // 0: proto.broker.CreateProjectRequest.project:type_name -> proto.project.Project
	5, // 1: proto.broker.CreateProjectRequest.template_requests:type_name -> proto.templates.TemplatesRequest
	6, // 2: proto.broker.CreateProjectResponse.status:type_name -> proto.templates.Status
	6, // 3: proto.broker.GetProjectStatusResponse.status:type_name -> proto.templates.Status
	7, // 4: proto.broker.GetProjectStatusResponse.template_responses:type_name -> proto.templates.TemplatesResponse
	0, // 5: proto.broker.BrokerService.CreateProject:input_type -> proto.broker.CreateProjectRequest
	2, // 6: proto.broker.BrokerService.GetProjectStatus:input_type -> proto.broker.GetProjectStatusRequest
	1, // 7: proto.broker.BrokerService.CreateProject:output_type -> proto.broker.CreateProjectResponse
	3, // 8: proto.broker.BrokerService.GetProjectStatus:output_type -> proto.broker.GetProjectStatusResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_broker_broker_proto_init() }
func file_proto_broker_broker_proto_init() {
	if File_proto_broker_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_broker_proto_rawDesc), len(file_proto_broker_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_broker_proto_depIdxs,
		MessageInfos:      file_proto_broker_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_broker_proto = out.File
	file_proto_broker_broker_proto_goTypes = nil
	file_proto_broker_broker_proto_depIdxs = nil
}
