// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v7.35.0
// source: proto/project/project.proto

package broker

import (
	templates "github.com/htemuri/azure-pulumi-service-broker/pkg/templates"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSPECIFIED RoleType = 0
	RoleType_ROLE_TYPE_ADMIN       RoleType = 1
	RoleType_ROLE_TYPE_DEVELOPER   RoleType = 2
	RoleType_ROLE_TYPE_READER      RoleType = 3
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNSPECIFIED",
		1: "ROLE_TYPE_ADMIN",
		2: "ROLE_TYPE_DEVELOPER",
		3: "ROLE_TYPE_READER",
	}
	RoleType_value = map[string]int32{
		"ROLE_TYPE_UNSPECIFIED": 0,
		"ROLE_TYPE_ADMIN":       1,
		"ROLE_TYPE_DEVELOPER":   2,
		"ROLE_TYPE_READER":      3,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_project_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_proto_project_project_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{0}
}

type StorageAccountSubResource int32

const (
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED StorageAccountSubResource = 0
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_BLOB        StorageAccountSubResource = 1
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_DFS         StorageAccountSubResource = 2
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE       StorageAccountSubResource = 3
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_FILE        StorageAccountSubResource = 4
	StorageAccountSubResource_STORAGE_ACCOUNT_SUB_RESOURCE_WEB         StorageAccountSubResource = 5
)

// Enum value maps for StorageAccountSubResource.
var (
	StorageAccountSubResource_name = map[int32]string{
		0: "STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED",
		1: "STORAGE_ACCOUNT_SUB_RESOURCE_BLOB",
		2: "STORAGE_ACCOUNT_SUB_RESOURCE_DFS",
		3: "STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE",
		4: "STORAGE_ACCOUNT_SUB_RESOURCE_FILE",
		5: "STORAGE_ACCOUNT_SUB_RESOURCE_WEB",
	}
	StorageAccountSubResource_value = map[string]int32{
		"STORAGE_ACCOUNT_SUB_RESOURCE_UNSPECIFIED": 0,
		"STORAGE_ACCOUNT_SUB_RESOURCE_BLOB":        1,
		"STORAGE_ACCOUNT_SUB_RESOURCE_DFS":         2,
		"STORAGE_ACCOUNT_SUB_RESOURCE_QUEUE":       3,
		"STORAGE_ACCOUNT_SUB_RESOURCE_FILE":        4,
		"STORAGE_ACCOUNT_SUB_RESOURCE_WEB":         5,
	}
)

func (x StorageAccountSubResource) Enum() *StorageAccountSubResource {
	p := new(StorageAccountSubResource)
	*p = x
	return p
}

func (x StorageAccountSubResource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageAccountSubResource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_project_project_proto_enumTypes[1].Descriptor()
}

func (StorageAccountSubResource) Type() protoreflect.EnumType {
	return &file_proto_project_project_proto_enumTypes[1]
}

func (x StorageAccountSubResource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageAccountSubResource.Descriptor instead.
func (StorageAccountSubResource) EnumDescriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{1}
}

type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Environment templates.Environment `protobuf:"varint,2,opt,name=environment,proto3,enum=proto.templates.Environment" json:"environment,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetEnvironment() templates.Environment {
	if x != nil {
		return x.Environment
	}
	return templates.Environment(0)
}

type ProjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TemplateResponses []*templates.TemplatesResponse `protobuf:"bytes,2,rep,name=template_responses,json=templateResponses,proto3" json:"template_responses,omitempty"`
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectResponse) GetTemplateResponses() []*templates.TemplatesResponse {
	if x != nil {
		return x.TemplateResponses
	}
	return nil
}

type UserPersonaEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role  RoleType `protobuf:"varint,1,opt,name=role,proto3,enum=proto.project.RoleType" json:"role,omitempty"`
	Users []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *UserPersonaEntry) Reset() {
	*x = UserPersonaEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPersonaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPersonaEntry) ProtoMessage() {}

func (x *UserPersonaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPersonaEntry.ProtoReflect.Descriptor instead.
func (*UserPersonaEntry) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *UserPersonaEntry) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ROLE_TYPE_UNSPECIFIED
}

func (x *UserPersonaEntry) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GroupPersonaEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role  RoleType `protobuf:"varint,1,opt,name=role,proto3,enum=proto.project.RoleType" json:"role,omitempty"`
	Group *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *GroupPersonaEntry) Reset() {
	*x = GroupPersonaEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupPersonaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPersonaEntry) ProtoMessage() {}

func (x *GroupPersonaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPersonaEntry.ProtoReflect.Descriptor instead.
func (*GroupPersonaEntry) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *GroupPersonaEntry) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_ROLE_TYPE_UNSPECIFIED
}

func (x *GroupPersonaEntry) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserPrincipalName string `protobuf:"bytes,1,opt,name=user_principal_name,json=userPrincipalName,proto3" json:"user_principal_name,omitempty"`
	ObjectId          string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetUserPrincipalName() string {
	if x != nil {
		return x.UserPrincipalName
	}
	return ""
}

func (x *User) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ObjectId    string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Group) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type StorageAccountOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled      bool                        `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SubResources []StorageAccountSubResource `protobuf:"varint,2,rep,packed,name=sub_resources,json=subResources,proto3,enum=proto.project.StorageAccountSubResource" json:"sub_resources,omitempty"`
}

func (x *StorageAccountOptions) Reset() {
	*x = StorageAccountOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageAccountOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageAccountOptions) ProtoMessage() {}

func (x *StorageAccountOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageAccountOptions.ProtoReflect.Descriptor instead.
func (*StorageAccountOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{6}
}

func (x *StorageAccountOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StorageAccountOptions) GetSubResources() []StorageAccountSubResource {
	if x != nil {
		return x.SubResources
	}
	return nil
}

type KeyVaultOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *KeyVaultOptions) Reset() {
	*x = KeyVaultOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyVaultOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVaultOptions) ProtoMessage() {}

func (x *KeyVaultOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVaultOptions.ProtoReflect.Descriptor instead.
func (*KeyVaultOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{7}
}

func (x *KeyVaultOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ServicePrincipalOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *ServicePrincipalOptions) Reset() {
	*x = ServicePrincipalOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicePrincipalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePrincipalOptions) ProtoMessage() {}

func (x *ServicePrincipalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePrincipalOptions.ProtoReflect.Descriptor instead.
func (*ServicePrincipalOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{8}
}

func (x *ServicePrincipalOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DataFactoryOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *DataFactoryOptions) Reset() {
	*x = DataFactoryOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_project_project_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataFactoryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFactoryOptions) ProtoMessage() {}

func (x *DataFactoryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_project_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFactoryOptions.ProtoReflect.Descriptor instead.
func (*DataFactoryOptions) Descriptor() ([]byte, []int) {
	return file_proto_project_project_proto_rawDescGZIP(), []int{9}
}

func (x *DataFactoryOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_proto_project_project_proto protoreflect.FileDescriptor

var file_proto_project_project_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x1c, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x78, 0x0a, 0x0f, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x51, 0x0a, 0x12, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x11, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22,
	0x6c, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x2a, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x53, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x47, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x15,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x4d, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x0c, 0x73, 0x75, 0x62, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x2b,
	0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x22, 0x2e, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x2a, 0x69, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15,
	0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x56, 0x45, 0x4c, 0x4f,
	0x50, 0x45, 0x52, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x8b, 0x02, 0x0a, 0x19,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x28, 0x53, 0x54, 0x4f,
	0x52, 0x41, 0x47, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42,
	0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x53, 0x54, 0x4f, 0x52, 0x41,
	0x47, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x52,
	0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x42, 0x4c, 0x4f, 0x42, 0x10, 0x01, 0x12, 0x24,
	0x0a, 0x20, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x44,
	0x46, 0x53, 0x10, 0x02, 0x12, 0x26, 0x0a, 0x22, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x53, 0x4f,
	0x55, 0x52, 0x43, 0x45, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x10, 0x03, 0x12, 0x25, 0x0a, 0x21,
	0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f,
	0x53, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x46, 0x49, 0x4c,
	0x45, 0x10, 0x04, 0x12, 0x24, 0x0a, 0x20, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x41,
	0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55,
	0x52, 0x43, 0x45, 0x5f, 0x57, 0x45, 0x42, 0x10, 0x05, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x74, 0x65, 0x6d, 0x75, 0x72, 0x69, 0x2f,
	0x61, 0x7a, 0x75, 0x72, 0x65, 0x2d, 0x70, 0x75, 0x6c, 0x75, 0x6d, 0x69, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_project_project_proto_rawDescOnce sync.Once
	file_proto_project_project_proto_rawDescData = file_proto_project_project_proto_rawDesc
)

func file_proto_project_project_proto_rawDescGZIP() []byte {
	file_proto_project_project_proto_rawDescOnce.Do(func() {
		file_proto_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_project_project_proto_rawDescData)
	})
	return file_proto_project_project_proto_rawDescData
}

var file_proto_project_project_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_project_project_proto_goTypes = []interface{}{
	(RoleType)(0),                       // 0: proto.project.RoleType
	(StorageAccountSubResource)(0),      // 1: proto.project.StorageAccountSubResource
	(*Project)(nil),                     // 2: proto.project.Project
	(*ProjectResponse)(nil),             // 3: proto.project.ProjectResponse
	(*UserPersonaEntry)(nil),            // 4: proto.project.UserPersonaEntry
	(*GroupPersonaEntry)(nil),           // 5: proto.project.GroupPersonaEntry
	(*User)(nil),                        // 6: proto.project.User
	(*Group)(nil),                       // 7: proto.project.Group
	(*StorageAccountOptions)(nil),       // 8: proto.project.StorageAccountOptions
	(*KeyVaultOptions)(nil),             // 9: proto.project.KeyVaultOptions
	(*ServicePrincipalOptions)(nil),     // 10: proto.project.ServicePrincipalOptions
	(*DataFactoryOptions)(nil),          // 11: proto.project.DataFactoryOptions
	(templates.Environment)(0),          // 12: proto.templates.Environment
	(*templates.TemplatesResponse)(nil), // 13: proto.templates.TemplatesResponse
}
var file_proto_project_project_proto_depIdxs = []int32{
	12, // 0: proto.project.Project.environment:type_name -> proto.templates.Environment
	13, // 1: proto.project.ProjectResponse.template_responses:type_name -> proto.templates.TemplatesResponse
	0,  // 2: proto.project.UserPersonaEntry.role:type_name -> proto.project.RoleType
	6,  // 3: proto.project.UserPersonaEntry.users:type_name -> proto.project.User
	0,  // 4: proto.project.GroupPersonaEntry.role:type_name -> proto.project.RoleType
	7,  // 5: proto.project.GroupPersonaEntry.group:type_name -> proto.project.Group
	1,  // 6: proto.project.StorageAccountOptions.sub_resources:type_name -> proto.project.StorageAccountSubResource
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_project_project_proto_init() }
func file_proto_project_project_proto_init() {
	if File_proto_project_project_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_project_project_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPersonaEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupPersonaEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageAccountOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyVaultOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicePrincipalOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_project_project_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataFactoryOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_project_project_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_project_project_proto_goTypes,
		DependencyIndexes: file_proto_project_project_proto_depIdxs,
		EnumInfos:         file_proto_project_project_proto_enumTypes,
		MessageInfos:      file_proto_project_project_proto_msgTypes,
	}.Build()
	File_proto_project_project_proto = out.File
	file_proto_project_project_proto_rawDesc = nil
	file_proto_project_project_proto_goTypes = nil
	file_proto_project_project_proto_depIdxs = nil
}
